// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: activity_logs.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_logs (
    shop_id, user_id, action, entity_type, entity_id, details, ip_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, shop_id, user_id, action, entity_type, entity_id, details, ip_address, created_at
`

type CreateActivityLogParams struct {
	ShopID     int64       `json:"shop_id"`
	UserID     pgtype.Int8 `json:"user_id"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.Int8 `json:"entity_id"`
	Details    pgtype.Text `json:"details"`
	IpAddress  pgtype.Text `json:"ip_address"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.ShopID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
		arg.IpAddress,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Details,
		&i.IpAddress,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityLogs = `-- name: ListActivityLogs :many
SELECT al.id, al.shop_id, al.user_id, al.action, al.entity_type, al.entity_id, al.details, al.ip_address, al.created_at, u.full_name as user_name, u.username
FROM activity_logs al
LEFT JOIN users u ON al.user_id = u.id
WHERE al.shop_id = $1
ORDER BY al.created_at DESC
LIMIT $2 OFFSET $3
`

type ListActivityLogsParams struct {
	ShopID int64 `json:"shop_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListActivityLogsRow struct {
	ID         int64              `json:"id"`
	ShopID     int64              `json:"shop_id"`
	UserID     pgtype.Int8        `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.Int8        `json:"entity_id"`
	Details    pgtype.Text        `json:"details"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UserName   pgtype.Text        `json:"user_name"`
	Username   pgtype.Text        `json:"username"`
}

func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ListActivityLogsRow, error) {
	rows, err := q.db.Query(ctx, listActivityLogs, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityLogsRow{}
	for rows.Next() {
		var i ListActivityLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
			&i.UserName,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
