// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*) FROM customers
WHERE shop_id = $1 
  AND is_active = true
  AND (
    $2::text = '' OR 
    first_name ILIKE '%' || $2 || '%' OR 
    last_name ILIKE '%' || $2 || '%' OR 
    phone ILIKE '%' || $2 || '%' OR
    city ILIKE '%' || $2 || '%' OR
    pin_code ILIKE '%' || $2 || '%'
  )
  AND (
    $3::text = 'all' OR
    ($3::text = 'with_dues' AND outstanding_dues > 0) OR
    ($3::text = 'without_dues' AND outstanding_dues = 0)
  )
  AND (
    $4::text = '' OR city ILIKE $4
  )
`

type CountCustomersParams struct {
	ShopID  int64  `json:"shop_id"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
}

func (q *Queries) CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers,
		arg.ShopID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    shop_id, first_name, last_name, phone, email, date_of_birth, gender,
    address_line1, address_line2, city, state, pin_code, profile_image_url, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, shop_id, first_name, last_name, phone, email, date_of_birth, gender, address_line1, address_line2, city, state, pin_code, profile_image_url, notes, total_spent, outstanding_dues, is_active, created_at, updated_at
`

type CreateCustomerParams struct {
	ShopID          int64       `json:"shop_id"`
	FirstName       string      `json:"first_name"`
	LastName        pgtype.Text `json:"last_name"`
	Phone           pgtype.Text `json:"phone"`
	Email           pgtype.Text `json:"email"`
	DateOfBirth     pgtype.Date `json:"date_of_birth"`
	Gender          pgtype.Text `json:"gender"`
	AddressLine1    pgtype.Text `json:"address_line1"`
	AddressLine2    pgtype.Text `json:"address_line2"`
	City            pgtype.Text `json:"city"`
	State           pgtype.Text `json:"state"`
	PinCode         pgtype.Text `json:"pin_code"`
	ProfileImageUrl pgtype.Text `json:"profile_image_url"`
	Notes           pgtype.Text `json:"notes"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.ShopID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Email,
		arg.DateOfBirth,
		arg.Gender,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PinCode,
		arg.ProfileImageUrl,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.DateOfBirth,
		&i.Gender,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PinCode,
		&i.ProfileImageUrl,
		&i.Notes,
		&i.TotalSpent,
		&i.OutstandingDues,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, shop_id, first_name, last_name, phone, email, date_of_birth, gender, address_line1, address_line2, city, state, pin_code, profile_image_url, notes, total_spent, outstanding_dues, is_active, created_at, updated_at FROM customers
WHERE id = $1 AND shop_id = $2 LIMIT 1
`

type GetCustomerByIDParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, arg.ID, arg.ShopID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.DateOfBirth,
		&i.Gender,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PinCode,
		&i.ProfileImageUrl,
		&i.Notes,
		&i.TotalSpent,
		&i.OutstandingDues,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerCities = `-- name: GetCustomerCities :many
SELECT DISTINCT city FROM customers
WHERE shop_id = $1 AND city != '' AND is_active = true
ORDER BY city ASC
`

func (q *Queries) GetCustomerCities(ctx context.Context, shopID int64) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, getCustomerCities, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Text{}
	for rows.Next() {
		var city pgtype.Text
		if err := rows.Scan(&city); err != nil {
			return nil, err
		}
		items = append(items, city)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerStats = `-- name: GetCustomerStats :one
SELECT 
    COUNT(*) AS total_in_book,
    COUNT(*) FILTER (WHERE created_at >= now() - INTERVAL '7 days') AS new_7d,
    COALESCE(SUM(outstanding_dues), 0)::decimal(12,2) AS total_outstanding
FROM customers
WHERE shop_id = $1 AND is_active = true
`

type GetCustomerStatsRow struct {
	TotalInBook      int64          `json:"total_in_book"`
	New7d            int64          `json:"new_7d"`
	TotalOutstanding pgtype.Numeric `json:"total_outstanding"`
}

func (q *Queries) GetCustomerStats(ctx context.Context, shopID int64) (GetCustomerStatsRow, error) {
	row := q.db.QueryRow(ctx, getCustomerStats, shopID)
	var i GetCustomerStatsRow
	err := row.Scan(&i.TotalInBook, &i.New7d, &i.TotalOutstanding)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, shop_id, first_name, last_name, phone, email, date_of_birth, gender, address_line1, address_line2, city, state, pin_code, profile_image_url, notes, total_spent, outstanding_dues, is_active, created_at, updated_at FROM customers
WHERE shop_id = $1 
  AND is_active = true
  AND (
    $2::text = '' OR 
    first_name ILIKE '%' || $2 || '%' OR 
    last_name ILIKE '%' || $2 || '%' OR 
    phone ILIKE '%' || $2 || '%' OR
    city ILIKE '%' || $2 || '%' OR
    pin_code ILIKE '%' || $2 || '%'
  )
  AND (
    $3::text = 'all' OR
    ($3::text = 'with_dues' AND outstanding_dues > 0) OR
    ($3::text = 'without_dues' AND outstanding_dues = 0)
  )
  AND (
    $4::text = '' OR city ILIKE $4
  )
ORDER BY 
  CASE WHEN $5::text = 'name_asc' THEN first_name END ASC,
  CASE WHEN $5::text = 'name_desc' THEN first_name END DESC,
  CASE WHEN $5::text = 'oldest' THEN id END ASC,
  CASE WHEN $5::text = 'newest' OR $5::text = '' THEN id END DESC
LIMIT $6 OFFSET $7
`

type ListCustomersParams struct {
	ShopID  int64  `json:"shop_id"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Column5 string `json:"column_5"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.ShopID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Email,
			&i.DateOfBirth,
			&i.Gender,
			&i.AddressLine1,
			&i.AddressLine2,
			&i.City,
			&i.State,
			&i.PinCode,
			&i.ProfileImageUrl,
			&i.Notes,
			&i.TotalSpent,
			&i.OutstandingDues,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerOutstandingDues = `-- name: SetCustomerOutstandingDues :exec
UPDATE customers
SET 
    outstanding_dues = $3,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
`

type SetCustomerOutstandingDuesParams struct {
	ID              int64          `json:"id"`
	ShopID          int64          `json:"shop_id"`
	OutstandingDues pgtype.Numeric `json:"outstanding_dues"`
}

func (q *Queries) SetCustomerOutstandingDues(ctx context.Context, arg SetCustomerOutstandingDuesParams) error {
	_, err := q.db.Exec(ctx, setCustomerOutstandingDues, arg.ID, arg.ShopID, arg.OutstandingDues)
	return err
}

const softDeleteCustomer = `-- name: SoftDeleteCustomer :exec
UPDATE customers
SET is_active = false, updated_at = now()
WHERE id = $1 AND shop_id = $2
`

type SoftDeleteCustomerParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

func (q *Queries) SoftDeleteCustomer(ctx context.Context, arg SoftDeleteCustomerParams) error {
	_, err := q.db.Exec(ctx, softDeleteCustomer, arg.ID, arg.ShopID)
	return err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET 
    first_name = $3,
    last_name = $4,
    phone = $5,
    email = $6,
    date_of_birth = $7,
    gender = $8,
    address_line1 = $9,
    address_line2 = $10,
    city = $11,
    state = $12,
    pin_code = $13,
    profile_image_url = $14,
    notes = $15,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, first_name, last_name, phone, email, date_of_birth, gender, address_line1, address_line2, city, state, pin_code, profile_image_url, notes, total_spent, outstanding_dues, is_active, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID              int64       `json:"id"`
	ShopID          int64       `json:"shop_id"`
	FirstName       string      `json:"first_name"`
	LastName        pgtype.Text `json:"last_name"`
	Phone           pgtype.Text `json:"phone"`
	Email           pgtype.Text `json:"email"`
	DateOfBirth     pgtype.Date `json:"date_of_birth"`
	Gender          pgtype.Text `json:"gender"`
	AddressLine1    pgtype.Text `json:"address_line1"`
	AddressLine2    pgtype.Text `json:"address_line2"`
	City            pgtype.Text `json:"city"`
	State           pgtype.Text `json:"state"`
	PinCode         pgtype.Text `json:"pin_code"`
	ProfileImageUrl pgtype.Text `json:"profile_image_url"`
	Notes           pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.ShopID,
		arg.FirstName,
		arg.LastName,
		arg.Phone,
		arg.Email,
		arg.DateOfBirth,
		arg.Gender,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PinCode,
		arg.ProfileImageUrl,
		arg.Notes,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.DateOfBirth,
		&i.Gender,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PinCode,
		&i.ProfileImageUrl,
		&i.Notes,
		&i.TotalSpent,
		&i.OutstandingDues,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomerFinancials = `-- name: UpdateCustomerFinancials :exec
UPDATE customers
SET 
    total_spent = total_spent + $3,
    outstanding_dues = outstanding_dues + $4,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
`

type UpdateCustomerFinancialsParams struct {
	ID              int64          `json:"id"`
	ShopID          int64          `json:"shop_id"`
	TotalSpent      pgtype.Numeric `json:"total_spent"`
	OutstandingDues pgtype.Numeric `json:"outstanding_dues"`
}

func (q *Queries) UpdateCustomerFinancials(ctx context.Context, arg UpdateCustomerFinancialsParams) error {
	_, err := q.db.Exec(ctx, updateCustomerFinancials,
		arg.ID,
		arg.ShopID,
		arg.TotalSpent,
		arg.OutstandingDues,
	)
	return err
}
