// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer_notes.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerNote = `-- name: CreateCustomerNote :one
INSERT INTO customer_notes (
    customer_id, user_id, note
) VALUES (
    $1, $2, $3
)
RETURNING id, customer_id, user_id, note, created_at
`

type CreateCustomerNoteParams struct {
	CustomerID int64       `json:"customer_id"`
	UserID     pgtype.Int8 `json:"user_id"`
	Note       string      `json:"note"`
}

func (q *Queries) CreateCustomerNote(ctx context.Context, arg CreateCustomerNoteParams) (CustomerNote, error) {
	row := q.db.QueryRow(ctx, createCustomerNote, arg.CustomerID, arg.UserID, arg.Note)
	var i CustomerNote
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.UserID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCustomerNote = `-- name: DeleteCustomerNote :exec
DELETE FROM customer_notes
WHERE id = $1
`

func (q *Queries) DeleteCustomerNote(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCustomerNote, id)
	return err
}

const listCustomerNotes = `-- name: ListCustomerNotes :many
SELECT cn.id, cn.customer_id, cn.user_id, cn.note, cn.created_at, u.full_name as author_name
FROM customer_notes cn
LEFT JOIN users u ON cn.user_id = u.id
WHERE cn.customer_id = $1
ORDER BY cn.created_at DESC
`

type ListCustomerNotesRow struct {
	ID         int64              `json:"id"`
	CustomerID int64              `json:"customer_id"`
	UserID     pgtype.Int8        `json:"user_id"`
	Note       string             `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AuthorName pgtype.Text        `json:"author_name"`
}

func (q *Queries) ListCustomerNotes(ctx context.Context, customerID int64) ([]ListCustomerNotesRow, error) {
	rows, err := q.db.Query(ctx, listCustomerNotes, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerNotesRow{}
	for rows.Next() {
		var i ListCustomerNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.UserID,
			&i.Note,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
