// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expense_categories.sql

package pgdb

import (
	"context"
)

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (
    shop_id, name, is_default
) VALUES (
    $1, $2, $3
)
RETURNING id, shop_id, name, is_default, created_at
`

type CreateExpenseCategoryParams struct {
	ShopID    int64  `json:"shop_id"`
	Name      string `json:"name"`
	IsDefault bool   `json:"is_default"`
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, createExpenseCategory, arg.ShopID, arg.Name, arg.IsDefault)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpenseCategory = `-- name: DeleteExpenseCategory :exec
DELETE FROM expense_categories
WHERE id = $1 AND shop_id = $2
`

type DeleteExpenseCategoryParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

func (q *Queries) DeleteExpenseCategory(ctx context.Context, arg DeleteExpenseCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteExpenseCategory, arg.ID, arg.ShopID)
	return err
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
SELECT id, shop_id, name, is_default, created_at FROM expense_categories
WHERE shop_id = $1
ORDER BY is_default DESC, name ASC
`

func (q *Queries) ListExpenseCategories(ctx context.Context, shopID int64) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listExpenseCategories, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpenseCategory{}
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
