// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: expenses.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExpenses = `-- name: CountExpenses :one
SELECT COUNT(*)
FROM expenses e
WHERE e.shop_id = $1
  AND ($2::bigint = 0 OR e.category_id = $2)
  AND ($3::text = 'all' OR e.expense_type = $3)
  AND ($4::date IS NULL OR e.expense_date >= $4)
  AND ($5::date IS NULL OR e.expense_date <= $5)
`

type CountExpensesParams struct {
	ShopID      int64       `json:"shop_id"`
	CategoryID  int64       `json:"category_id"`
	ExpenseType string      `json:"expense_type"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
}

func (q *Queries) CountExpenses(ctx context.Context, arg CountExpensesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExpenses,
		arg.ShopID,
		arg.CategoryID,
		arg.ExpenseType,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
    shop_id, category_id, title, amount, expense_date, payment_mode,
    expense_type, recurrence, receipt_url, notes, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
RETURNING id, shop_id, category_id, title, amount, expense_date, payment_mode, expense_type, recurrence, receipt_url, notes, created_by, created_at, updated_at
`

type CreateExpenseParams struct {
	ShopID      int64          `json:"shop_id"`
	CategoryID  pgtype.Int8    `json:"category_id"`
	Title       string         `json:"title"`
	Amount      pgtype.Numeric `json:"amount"`
	ExpenseDate pgtype.Date    `json:"expense_date"`
	PaymentMode string         `json:"payment_mode"`
	ExpenseType string         `json:"expense_type"`
	Recurrence  pgtype.Text    `json:"recurrence"`
	ReceiptUrl  pgtype.Text    `json:"receipt_url"`
	Notes       pgtype.Text    `json:"notes"`
	CreatedBy   pgtype.Int8    `json:"created_by"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.ShopID,
		arg.CategoryID,
		arg.Title,
		arg.Amount,
		arg.ExpenseDate,
		arg.PaymentMode,
		arg.ExpenseType,
		arg.Recurrence,
		arg.ReceiptUrl,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.Title,
		&i.Amount,
		&i.ExpenseDate,
		&i.PaymentMode,
		&i.ExpenseType,
		&i.Recurrence,
		&i.ReceiptUrl,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1 AND shop_id = $2
`

type DeleteExpenseParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.ShopID)
	return err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT e.id, e.shop_id, e.category_id, e.title, e.amount, e.expense_date, e.payment_mode, e.expense_type, e.recurrence, e.receipt_url, e.notes, e.created_by, e.created_at, e.updated_at, ec.name as category_name, u.full_name as created_by_name
FROM expenses e
LEFT JOIN expense_categories ec ON e.category_id = ec.id
LEFT JOIN users u ON e.created_by = u.id
WHERE e.id = $1 AND e.shop_id = $2 LIMIT 1
`

type GetExpenseByIDParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

type GetExpenseByIDRow struct {
	ID            int64              `json:"id"`
	ShopID        int64              `json:"shop_id"`
	CategoryID    pgtype.Int8        `json:"category_id"`
	Title         string             `json:"title"`
	Amount        pgtype.Numeric     `json:"amount"`
	ExpenseDate   pgtype.Date        `json:"expense_date"`
	PaymentMode   string             `json:"payment_mode"`
	ExpenseType   string             `json:"expense_type"`
	Recurrence    pgtype.Text        `json:"recurrence"`
	ReceiptUrl    pgtype.Text        `json:"receipt_url"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategoryName  pgtype.Text        `json:"category_name"`
	CreatedByName pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (GetExpenseByIDRow, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, arg.ID, arg.ShopID)
	var i GetExpenseByIDRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.Title,
		&i.Amount,
		&i.ExpenseDate,
		&i.PaymentMode,
		&i.ExpenseType,
		&i.Recurrence,
		&i.ReceiptUrl,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CreatedByName,
	)
	return i, err
}

const getExpensesSummary = `-- name: GetExpensesSummary :one
SELECT 
    COALESCE(SUM(amount), 0)::decimal(12,2) AS total_amount,
    COALESCE(SUM(amount) FILTER (WHERE expense_type = 'one_time'), 0)::decimal(12,2) AS one_time_amount,
    COALESCE(SUM(amount) FILTER (WHERE expense_type = 'recurring'), 0)::decimal(12,2) AS recurring_amount
FROM expenses
WHERE shop_id = $1
  AND ($2::date IS NULL OR expense_date >= $2)
  AND ($3::date IS NULL OR expense_date <= $3)
`

type GetExpensesSummaryParams struct {
	ShopID   int64       `json:"shop_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type GetExpensesSummaryRow struct {
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	OneTimeAmount   pgtype.Numeric `json:"one_time_amount"`
	RecurringAmount pgtype.Numeric `json:"recurring_amount"`
}

func (q *Queries) GetExpensesSummary(ctx context.Context, arg GetExpensesSummaryParams) (GetExpensesSummaryRow, error) {
	row := q.db.QueryRow(ctx, getExpensesSummary, arg.ShopID, arg.FromDate, arg.ToDate)
	var i GetExpensesSummaryRow
	err := row.Scan(&i.TotalAmount, &i.OneTimeAmount, &i.RecurringAmount)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT e.id, e.shop_id, e.category_id, e.title, e.amount, e.expense_date, e.payment_mode, e.expense_type, e.recurrence, e.receipt_url, e.notes, e.created_by, e.created_at, e.updated_at, ec.name as category_name, u.full_name as created_by_name
FROM expenses e
LEFT JOIN expense_categories ec ON e.category_id = ec.id
LEFT JOIN users u ON e.created_by = u.id
WHERE e.shop_id = $1
  AND ($2::bigint = 0 OR e.category_id = $2)
  AND ($3::text = 'all' OR e.expense_type = $3)
  AND ($4::date IS NULL OR e.expense_date >= $4)
  AND ($5::date IS NULL OR e.expense_date <= $5)
ORDER BY e.expense_date DESC, e.id DESC
LIMIT $7 OFFSET $6
`

type ListExpensesParams struct {
	ShopID      int64       `json:"shop_id"`
	CategoryID  int64       `json:"category_id"`
	ExpenseType string      `json:"expense_type"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListExpensesRow struct {
	ID            int64              `json:"id"`
	ShopID        int64              `json:"shop_id"`
	CategoryID    pgtype.Int8        `json:"category_id"`
	Title         string             `json:"title"`
	Amount        pgtype.Numeric     `json:"amount"`
	ExpenseDate   pgtype.Date        `json:"expense_date"`
	PaymentMode   string             `json:"payment_mode"`
	ExpenseType   string             `json:"expense_type"`
	Recurrence    pgtype.Text        `json:"recurrence"`
	ReceiptUrl    pgtype.Text        `json:"receipt_url"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	CategoryName  pgtype.Text        `json:"category_name"`
	CreatedByName pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.ShopID,
		arg.CategoryID,
		arg.ExpenseType,
		arg.FromDate,
		arg.ToDate,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesRow{}
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CategoryID,
			&i.Title,
			&i.Amount,
			&i.ExpenseDate,
			&i.PaymentMode,
			&i.ExpenseType,
			&i.Recurrence,
			&i.ReceiptUrl,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET 
    category_id = $3,
    title = $4,
    amount = $5,
    expense_date = $6,
    payment_mode = $7,
    expense_type = $8,
    recurrence = $9,
    receipt_url = $10,
    notes = $11,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, category_id, title, amount, expense_date, payment_mode, expense_type, recurrence, receipt_url, notes, created_by, created_at, updated_at
`

type UpdateExpenseParams struct {
	ID          int64          `json:"id"`
	ShopID      int64          `json:"shop_id"`
	CategoryID  pgtype.Int8    `json:"category_id"`
	Title       string         `json:"title"`
	Amount      pgtype.Numeric `json:"amount"`
	ExpenseDate pgtype.Date    `json:"expense_date"`
	PaymentMode string         `json:"payment_mode"`
	ExpenseType string         `json:"expense_type"`
	Recurrence  pgtype.Text    `json:"recurrence"`
	ReceiptUrl  pgtype.Text    `json:"receipt_url"`
	Notes       pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.ShopID,
		arg.CategoryID,
		arg.Title,
		arg.Amount,
		arg.ExpenseDate,
		arg.PaymentMode,
		arg.ExpenseType,
		arg.Recurrence,
		arg.ReceiptUrl,
		arg.Notes,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CategoryID,
		&i.Title,
		&i.Amount,
		&i.ExpenseDate,
		&i.PaymentMode,
		&i.ExpenseType,
		&i.Recurrence,
		&i.ReceiptUrl,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
