// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: eye_tests.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEyeTests = `-- name: CountEyeTests :one
SELECT COUNT(*)
FROM eye_tests et
JOIN customers c ON et.customer_id = c.id
WHERE et.shop_id = $1
  AND (
    $2::text = '' OR
    et.test_number ILIKE '%' || $2 || '%' OR
    c.first_name ILIKE '%' || $2 || '%' OR
    c.last_name ILIKE '%' || $2 || '%' OR
    c.phone ILIKE '%' || $2 || '%'
  )
  AND ($3::timestamptz IS NULL OR et.test_date >= $3)
  AND ($4::timestamptz IS NULL OR et.test_date <= $4)
`

type CountEyeTestsParams struct {
	ShopID  int64              `json:"shop_id"`
	Column2 string             `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
}

func (q *Queries) CountEyeTests(ctx context.Context, arg CountEyeTestsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEyeTests,
		arg.ShopID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEyeTest = `-- name: CreateEyeTest :one
INSERT INTO eye_tests (
    shop_id, customer_id, tested_by, test_number, test_date,
    checkup_by_type, doctor_name, hospital_name, doctor_city,
    optical_shop_name, optical_city, examiner_name,
    re_sph, re_cyl, re_axis, re_add, re_pd, re_prism, re_prism_base, re_visual_acuity,
    le_sph, le_cyl, le_axis, le_add, le_pd, le_prism, le_prism_base, le_visual_acuity,
    total_pd, notes
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28,
    $29, $30
)
RETURNING id, shop_id, customer_id, tested_by, test_number, test_date, checkup_by_type, doctor_name, hospital_name, doctor_city, optical_shop_name, optical_city, examiner_name, re_sph, re_cyl, re_axis, re_add, re_pd, re_prism, re_prism_base, re_visual_acuity, le_sph, le_cyl, le_axis, le_add, le_pd, le_prism, le_prism_base, le_visual_acuity, total_pd, notes, created_at, updated_at
`

type CreateEyeTestParams struct {
	ShopID          int64              `json:"shop_id"`
	CustomerID      int64              `json:"customer_id"`
	TestedBy        pgtype.Int8        `json:"tested_by"`
	TestNumber      string             `json:"test_number"`
	TestDate        pgtype.Timestamptz `json:"test_date"`
	CheckupByType   pgtype.Text        `json:"checkup_by_type"`
	DoctorName      pgtype.Text        `json:"doctor_name"`
	HospitalName    pgtype.Text        `json:"hospital_name"`
	DoctorCity      pgtype.Text        `json:"doctor_city"`
	OpticalShopName pgtype.Text        `json:"optical_shop_name"`
	OpticalCity     pgtype.Text        `json:"optical_city"`
	ExaminerName    pgtype.Text        `json:"examiner_name"`
	ReSph           pgtype.Numeric     `json:"re_sph"`
	ReCyl           pgtype.Numeric     `json:"re_cyl"`
	ReAxis          pgtype.Int4        `json:"re_axis"`
	ReAdd           pgtype.Numeric     `json:"re_add"`
	RePd            pgtype.Numeric     `json:"re_pd"`
	RePrism         pgtype.Numeric     `json:"re_prism"`
	RePrismBase     pgtype.Text        `json:"re_prism_base"`
	ReVisualAcuity  pgtype.Text        `json:"re_visual_acuity"`
	LeSph           pgtype.Numeric     `json:"le_sph"`
	LeCyl           pgtype.Numeric     `json:"le_cyl"`
	LeAxis          pgtype.Int4        `json:"le_axis"`
	LeAdd           pgtype.Numeric     `json:"le_add"`
	LePd            pgtype.Numeric     `json:"le_pd"`
	LePrism         pgtype.Numeric     `json:"le_prism"`
	LePrismBase     pgtype.Text        `json:"le_prism_base"`
	LeVisualAcuity  pgtype.Text        `json:"le_visual_acuity"`
	TotalPd         pgtype.Numeric     `json:"total_pd"`
	Notes           pgtype.Text        `json:"notes"`
}

func (q *Queries) CreateEyeTest(ctx context.Context, arg CreateEyeTestParams) (EyeTest, error) {
	row := q.db.QueryRow(ctx, createEyeTest,
		arg.ShopID,
		arg.CustomerID,
		arg.TestedBy,
		arg.TestNumber,
		arg.TestDate,
		arg.CheckupByType,
		arg.DoctorName,
		arg.HospitalName,
		arg.DoctorCity,
		arg.OpticalShopName,
		arg.OpticalCity,
		arg.ExaminerName,
		arg.ReSph,
		arg.ReCyl,
		arg.ReAxis,
		arg.ReAdd,
		arg.RePd,
		arg.RePrism,
		arg.RePrismBase,
		arg.ReVisualAcuity,
		arg.LeSph,
		arg.LeCyl,
		arg.LeAxis,
		arg.LeAdd,
		arg.LePd,
		arg.LePrism,
		arg.LePrismBase,
		arg.LeVisualAcuity,
		arg.TotalPd,
		arg.Notes,
	)
	var i EyeTest
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.TestedBy,
		&i.TestNumber,
		&i.TestDate,
		&i.CheckupByType,
		&i.DoctorName,
		&i.HospitalName,
		&i.DoctorCity,
		&i.OpticalShopName,
		&i.OpticalCity,
		&i.ExaminerName,
		&i.ReSph,
		&i.ReCyl,
		&i.ReAxis,
		&i.ReAdd,
		&i.RePd,
		&i.RePrism,
		&i.RePrismBase,
		&i.ReVisualAcuity,
		&i.LeSph,
		&i.LeCyl,
		&i.LeAxis,
		&i.LeAdd,
		&i.LePd,
		&i.LePrism,
		&i.LePrismBase,
		&i.LeVisualAcuity,
		&i.TotalPd,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEyeTest = `-- name: DeleteEyeTest :exec
DELETE FROM eye_tests
WHERE id = $1 AND shop_id = $2
`

type DeleteEyeTestParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

func (q *Queries) DeleteEyeTest(ctx context.Context, arg DeleteEyeTestParams) error {
	_, err := q.db.Exec(ctx, deleteEyeTest, arg.ID, arg.ShopID)
	return err
}

const getEyeTestByID = `-- name: GetEyeTestByID :one
SELECT et.id, et.shop_id, et.customer_id, et.tested_by, et.test_number, et.test_date, et.checkup_by_type, et.doctor_name, et.hospital_name, et.doctor_city, et.optical_shop_name, et.optical_city, et.examiner_name, et.re_sph, et.re_cyl, et.re_axis, et.re_add, et.re_pd, et.re_prism, et.re_prism_base, et.re_visual_acuity, et.le_sph, et.le_cyl, et.le_axis, et.le_add, et.le_pd, et.le_prism, et.le_prism_base, et.le_visual_acuity, et.total_pd, et.notes, et.created_at, et.updated_at, c.first_name, c.last_name, c.phone as customer_phone, u.full_name as tested_by_name
FROM eye_tests et
JOIN customers c ON et.customer_id = c.id
LEFT JOIN users u ON et.tested_by = u.id
WHERE et.id = $1 AND et.shop_id = $2 LIMIT 1
`

type GetEyeTestByIDParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

type GetEyeTestByIDRow struct {
	ID              int64              `json:"id"`
	ShopID          int64              `json:"shop_id"`
	CustomerID      int64              `json:"customer_id"`
	TestedBy        pgtype.Int8        `json:"tested_by"`
	TestNumber      string             `json:"test_number"`
	TestDate        pgtype.Timestamptz `json:"test_date"`
	CheckupByType   pgtype.Text        `json:"checkup_by_type"`
	DoctorName      pgtype.Text        `json:"doctor_name"`
	HospitalName    pgtype.Text        `json:"hospital_name"`
	DoctorCity      pgtype.Text        `json:"doctor_city"`
	OpticalShopName pgtype.Text        `json:"optical_shop_name"`
	OpticalCity     pgtype.Text        `json:"optical_city"`
	ExaminerName    pgtype.Text        `json:"examiner_name"`
	ReSph           pgtype.Numeric     `json:"re_sph"`
	ReCyl           pgtype.Numeric     `json:"re_cyl"`
	ReAxis          pgtype.Int4        `json:"re_axis"`
	ReAdd           pgtype.Numeric     `json:"re_add"`
	RePd            pgtype.Numeric     `json:"re_pd"`
	RePrism         pgtype.Numeric     `json:"re_prism"`
	RePrismBase     pgtype.Text        `json:"re_prism_base"`
	ReVisualAcuity  pgtype.Text        `json:"re_visual_acuity"`
	LeSph           pgtype.Numeric     `json:"le_sph"`
	LeCyl           pgtype.Numeric     `json:"le_cyl"`
	LeAxis          pgtype.Int4        `json:"le_axis"`
	LeAdd           pgtype.Numeric     `json:"le_add"`
	LePd            pgtype.Numeric     `json:"le_pd"`
	LePrism         pgtype.Numeric     `json:"le_prism"`
	LePrismBase     pgtype.Text        `json:"le_prism_base"`
	LeVisualAcuity  pgtype.Text        `json:"le_visual_acuity"`
	TotalPd         pgtype.Numeric     `json:"total_pd"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FirstName       string             `json:"first_name"`
	LastName        pgtype.Text        `json:"last_name"`
	CustomerPhone   pgtype.Text        `json:"customer_phone"`
	TestedByName    pgtype.Text        `json:"tested_by_name"`
}

func (q *Queries) GetEyeTestByID(ctx context.Context, arg GetEyeTestByIDParams) (GetEyeTestByIDRow, error) {
	row := q.db.QueryRow(ctx, getEyeTestByID, arg.ID, arg.ShopID)
	var i GetEyeTestByIDRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.TestedBy,
		&i.TestNumber,
		&i.TestDate,
		&i.CheckupByType,
		&i.DoctorName,
		&i.HospitalName,
		&i.DoctorCity,
		&i.OpticalShopName,
		&i.OpticalCity,
		&i.ExaminerName,
		&i.ReSph,
		&i.ReCyl,
		&i.ReAxis,
		&i.ReAdd,
		&i.RePd,
		&i.RePrism,
		&i.RePrismBase,
		&i.ReVisualAcuity,
		&i.LeSph,
		&i.LeCyl,
		&i.LeAxis,
		&i.LeAdd,
		&i.LePd,
		&i.LePrism,
		&i.LePrismBase,
		&i.LeVisualAcuity,
		&i.TotalPd,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.CustomerPhone,
		&i.TestedByName,
	)
	return i, err
}

const listEyeTests = `-- name: ListEyeTests :many
SELECT et.id, et.shop_id, et.customer_id, et.tested_by, et.test_number, et.test_date, et.checkup_by_type, et.doctor_name, et.hospital_name, et.doctor_city, et.optical_shop_name, et.optical_city, et.examiner_name, et.re_sph, et.re_cyl, et.re_axis, et.re_add, et.re_pd, et.re_prism, et.re_prism_base, et.re_visual_acuity, et.le_sph, et.le_cyl, et.le_axis, et.le_add, et.le_pd, et.le_prism, et.le_prism_base, et.le_visual_acuity, et.total_pd, et.notes, et.created_at, et.updated_at, c.first_name, c.last_name, c.phone as customer_phone, u.full_name as tested_by_name
FROM eye_tests et
JOIN customers c ON et.customer_id = c.id
LEFT JOIN users u ON et.tested_by = u.id
WHERE et.shop_id = $1
  AND (
    $2::text = '' OR
    et.test_number ILIKE '%' || $2 || '%' OR
    c.first_name ILIKE '%' || $2 || '%' OR
    c.last_name ILIKE '%' || $2 || '%' OR
    c.phone ILIKE '%' || $2 || '%'
  )
  AND ($3::timestamptz IS NULL OR et.test_date >= $3)
  AND ($4::timestamptz IS NULL OR et.test_date <= $4)
ORDER BY et.test_date DESC
LIMIT $5 OFFSET $6
`

type ListEyeTestsParams struct {
	ShopID  int64              `json:"shop_id"`
	Column2 string             `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Column4 pgtype.Timestamptz `json:"column_4"`
	Limit   int32              `json:"limit"`
	Offset  int32              `json:"offset"`
}

type ListEyeTestsRow struct {
	ID              int64              `json:"id"`
	ShopID          int64              `json:"shop_id"`
	CustomerID      int64              `json:"customer_id"`
	TestedBy        pgtype.Int8        `json:"tested_by"`
	TestNumber      string             `json:"test_number"`
	TestDate        pgtype.Timestamptz `json:"test_date"`
	CheckupByType   pgtype.Text        `json:"checkup_by_type"`
	DoctorName      pgtype.Text        `json:"doctor_name"`
	HospitalName    pgtype.Text        `json:"hospital_name"`
	DoctorCity      pgtype.Text        `json:"doctor_city"`
	OpticalShopName pgtype.Text        `json:"optical_shop_name"`
	OpticalCity     pgtype.Text        `json:"optical_city"`
	ExaminerName    pgtype.Text        `json:"examiner_name"`
	ReSph           pgtype.Numeric     `json:"re_sph"`
	ReCyl           pgtype.Numeric     `json:"re_cyl"`
	ReAxis          pgtype.Int4        `json:"re_axis"`
	ReAdd           pgtype.Numeric     `json:"re_add"`
	RePd            pgtype.Numeric     `json:"re_pd"`
	RePrism         pgtype.Numeric     `json:"re_prism"`
	RePrismBase     pgtype.Text        `json:"re_prism_base"`
	ReVisualAcuity  pgtype.Text        `json:"re_visual_acuity"`
	LeSph           pgtype.Numeric     `json:"le_sph"`
	LeCyl           pgtype.Numeric     `json:"le_cyl"`
	LeAxis          pgtype.Int4        `json:"le_axis"`
	LeAdd           pgtype.Numeric     `json:"le_add"`
	LePd            pgtype.Numeric     `json:"le_pd"`
	LePrism         pgtype.Numeric     `json:"le_prism"`
	LePrismBase     pgtype.Text        `json:"le_prism_base"`
	LeVisualAcuity  pgtype.Text        `json:"le_visual_acuity"`
	TotalPd         pgtype.Numeric     `json:"total_pd"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	FirstName       string             `json:"first_name"`
	LastName        pgtype.Text        `json:"last_name"`
	CustomerPhone   pgtype.Text        `json:"customer_phone"`
	TestedByName    pgtype.Text        `json:"tested_by_name"`
}

func (q *Queries) ListEyeTests(ctx context.Context, arg ListEyeTestsParams) ([]ListEyeTestsRow, error) {
	rows, err := q.db.Query(ctx, listEyeTests,
		arg.ShopID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEyeTestsRow{}
	for rows.Next() {
		var i ListEyeTestsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CustomerID,
			&i.TestedBy,
			&i.TestNumber,
			&i.TestDate,
			&i.CheckupByType,
			&i.DoctorName,
			&i.HospitalName,
			&i.DoctorCity,
			&i.OpticalShopName,
			&i.OpticalCity,
			&i.ExaminerName,
			&i.ReSph,
			&i.ReCyl,
			&i.ReAxis,
			&i.ReAdd,
			&i.RePd,
			&i.RePrism,
			&i.RePrismBase,
			&i.ReVisualAcuity,
			&i.LeSph,
			&i.LeCyl,
			&i.LeAxis,
			&i.LeAdd,
			&i.LePd,
			&i.LePrism,
			&i.LePrismBase,
			&i.LeVisualAcuity,
			&i.TotalPd,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.CustomerPhone,
			&i.TestedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEyeTestsByCustomer = `-- name: ListEyeTestsByCustomer :many
SELECT et.id, et.shop_id, et.customer_id, et.tested_by, et.test_number, et.test_date, et.checkup_by_type, et.doctor_name, et.hospital_name, et.doctor_city, et.optical_shop_name, et.optical_city, et.examiner_name, et.re_sph, et.re_cyl, et.re_axis, et.re_add, et.re_pd, et.re_prism, et.re_prism_base, et.re_visual_acuity, et.le_sph, et.le_cyl, et.le_axis, et.le_add, et.le_pd, et.le_prism, et.le_prism_base, et.le_visual_acuity, et.total_pd, et.notes, et.created_at, et.updated_at, u.full_name as tested_by_name
FROM eye_tests et
LEFT JOIN users u ON et.tested_by = u.id
WHERE et.customer_id = $1 AND et.shop_id = $2
ORDER BY et.test_date DESC
`

type ListEyeTestsByCustomerParams struct {
	CustomerID int64 `json:"customer_id"`
	ShopID     int64 `json:"shop_id"`
}

type ListEyeTestsByCustomerRow struct {
	ID              int64              `json:"id"`
	ShopID          int64              `json:"shop_id"`
	CustomerID      int64              `json:"customer_id"`
	TestedBy        pgtype.Int8        `json:"tested_by"`
	TestNumber      string             `json:"test_number"`
	TestDate        pgtype.Timestamptz `json:"test_date"`
	CheckupByType   pgtype.Text        `json:"checkup_by_type"`
	DoctorName      pgtype.Text        `json:"doctor_name"`
	HospitalName    pgtype.Text        `json:"hospital_name"`
	DoctorCity      pgtype.Text        `json:"doctor_city"`
	OpticalShopName pgtype.Text        `json:"optical_shop_name"`
	OpticalCity     pgtype.Text        `json:"optical_city"`
	ExaminerName    pgtype.Text        `json:"examiner_name"`
	ReSph           pgtype.Numeric     `json:"re_sph"`
	ReCyl           pgtype.Numeric     `json:"re_cyl"`
	ReAxis          pgtype.Int4        `json:"re_axis"`
	ReAdd           pgtype.Numeric     `json:"re_add"`
	RePd            pgtype.Numeric     `json:"re_pd"`
	RePrism         pgtype.Numeric     `json:"re_prism"`
	RePrismBase     pgtype.Text        `json:"re_prism_base"`
	ReVisualAcuity  pgtype.Text        `json:"re_visual_acuity"`
	LeSph           pgtype.Numeric     `json:"le_sph"`
	LeCyl           pgtype.Numeric     `json:"le_cyl"`
	LeAxis          pgtype.Int4        `json:"le_axis"`
	LeAdd           pgtype.Numeric     `json:"le_add"`
	LePd            pgtype.Numeric     `json:"le_pd"`
	LePrism         pgtype.Numeric     `json:"le_prism"`
	LePrismBase     pgtype.Text        `json:"le_prism_base"`
	LeVisualAcuity  pgtype.Text        `json:"le_visual_acuity"`
	TotalPd         pgtype.Numeric     `json:"total_pd"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TestedByName    pgtype.Text        `json:"tested_by_name"`
}

func (q *Queries) ListEyeTestsByCustomer(ctx context.Context, arg ListEyeTestsByCustomerParams) ([]ListEyeTestsByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listEyeTestsByCustomer, arg.CustomerID, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEyeTestsByCustomerRow{}
	for rows.Next() {
		var i ListEyeTestsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CustomerID,
			&i.TestedBy,
			&i.TestNumber,
			&i.TestDate,
			&i.CheckupByType,
			&i.DoctorName,
			&i.HospitalName,
			&i.DoctorCity,
			&i.OpticalShopName,
			&i.OpticalCity,
			&i.ExaminerName,
			&i.ReSph,
			&i.ReCyl,
			&i.ReAxis,
			&i.ReAdd,
			&i.RePd,
			&i.RePrism,
			&i.RePrismBase,
			&i.ReVisualAcuity,
			&i.LeSph,
			&i.LeCyl,
			&i.LeAxis,
			&i.LeAdd,
			&i.LePd,
			&i.LePrism,
			&i.LePrismBase,
			&i.LeVisualAcuity,
			&i.TotalPd,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TestedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEyeTest = `-- name: UpdateEyeTest :one
UPDATE eye_tests
SET 
    tested_by = $3,
    test_date = $4,
    checkup_by_type = $5,
    doctor_name = $6,
    hospital_name = $7,
    doctor_city = $8,
    optical_shop_name = $9,
    optical_city = $10,
    examiner_name = $11,
    re_sph = $12,
    re_cyl = $13,
    re_axis = $14,
    re_add = $15,
    re_pd = $16,
    re_prism = $17,
    re_prism_base = $18,
    re_visual_acuity = $19,
    le_sph = $20,
    le_cyl = $21,
    le_axis = $22,
    le_add = $23,
    le_pd = $24,
    le_prism = $25,
    le_prism_base = $26,
    le_visual_acuity = $27,
    total_pd = $28,
    notes = $29,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, customer_id, tested_by, test_number, test_date, checkup_by_type, doctor_name, hospital_name, doctor_city, optical_shop_name, optical_city, examiner_name, re_sph, re_cyl, re_axis, re_add, re_pd, re_prism, re_prism_base, re_visual_acuity, le_sph, le_cyl, le_axis, le_add, le_pd, le_prism, le_prism_base, le_visual_acuity, total_pd, notes, created_at, updated_at
`

type UpdateEyeTestParams struct {
	ID              int64              `json:"id"`
	ShopID          int64              `json:"shop_id"`
	TestedBy        pgtype.Int8        `json:"tested_by"`
	TestDate        pgtype.Timestamptz `json:"test_date"`
	CheckupByType   pgtype.Text        `json:"checkup_by_type"`
	DoctorName      pgtype.Text        `json:"doctor_name"`
	HospitalName    pgtype.Text        `json:"hospital_name"`
	DoctorCity      pgtype.Text        `json:"doctor_city"`
	OpticalShopName pgtype.Text        `json:"optical_shop_name"`
	OpticalCity     pgtype.Text        `json:"optical_city"`
	ExaminerName    pgtype.Text        `json:"examiner_name"`
	ReSph           pgtype.Numeric     `json:"re_sph"`
	ReCyl           pgtype.Numeric     `json:"re_cyl"`
	ReAxis          pgtype.Int4        `json:"re_axis"`
	ReAdd           pgtype.Numeric     `json:"re_add"`
	RePd            pgtype.Numeric     `json:"re_pd"`
	RePrism         pgtype.Numeric     `json:"re_prism"`
	RePrismBase     pgtype.Text        `json:"re_prism_base"`
	ReVisualAcuity  pgtype.Text        `json:"re_visual_acuity"`
	LeSph           pgtype.Numeric     `json:"le_sph"`
	LeCyl           pgtype.Numeric     `json:"le_cyl"`
	LeAxis          pgtype.Int4        `json:"le_axis"`
	LeAdd           pgtype.Numeric     `json:"le_add"`
	LePd            pgtype.Numeric     `json:"le_pd"`
	LePrism         pgtype.Numeric     `json:"le_prism"`
	LePrismBase     pgtype.Text        `json:"le_prism_base"`
	LeVisualAcuity  pgtype.Text        `json:"le_visual_acuity"`
	TotalPd         pgtype.Numeric     `json:"total_pd"`
	Notes           pgtype.Text        `json:"notes"`
}

func (q *Queries) UpdateEyeTest(ctx context.Context, arg UpdateEyeTestParams) (EyeTest, error) {
	row := q.db.QueryRow(ctx, updateEyeTest,
		arg.ID,
		arg.ShopID,
		arg.TestedBy,
		arg.TestDate,
		arg.CheckupByType,
		arg.DoctorName,
		arg.HospitalName,
		arg.DoctorCity,
		arg.OpticalShopName,
		arg.OpticalCity,
		arg.ExaminerName,
		arg.ReSph,
		arg.ReCyl,
		arg.ReAxis,
		arg.ReAdd,
		arg.RePd,
		arg.RePrism,
		arg.RePrismBase,
		arg.ReVisualAcuity,
		arg.LeSph,
		arg.LeCyl,
		arg.LeAxis,
		arg.LeAdd,
		arg.LePd,
		arg.LePrism,
		arg.LePrismBase,
		arg.LeVisualAcuity,
		arg.TotalPd,
		arg.Notes,
	)
	var i EyeTest
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.TestedBy,
		&i.TestNumber,
		&i.TestDate,
		&i.CheckupByType,
		&i.DoctorName,
		&i.HospitalName,
		&i.DoctorCity,
		&i.OpticalShopName,
		&i.OpticalCity,
		&i.ExaminerName,
		&i.ReSph,
		&i.ReCyl,
		&i.ReAxis,
		&i.ReAdd,
		&i.RePd,
		&i.RePrism,
		&i.RePrismBase,
		&i.ReVisualAcuity,
		&i.LeSph,
		&i.LeCyl,
		&i.LeAxis,
		&i.LeAdd,
		&i.LePd,
		&i.LePrism,
		&i.LePrismBase,
		&i.LeVisualAcuity,
		&i.TotalPd,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
