// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityLog struct {
	ID         int64              `json:"id"`
	ShopID     int64              `json:"shop_id"`
	UserID     pgtype.Int8        `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.Int8        `json:"entity_id"`
	Details    pgtype.Text        `json:"details"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Customer struct {
	ID              int64              `json:"id"`
	ShopID          int64              `json:"shop_id"`
	FirstName       string             `json:"first_name"`
	LastName        pgtype.Text        `json:"last_name"`
	Phone           pgtype.Text        `json:"phone"`
	Email           pgtype.Text        `json:"email"`
	DateOfBirth     pgtype.Date        `json:"date_of_birth"`
	Gender          pgtype.Text        `json:"gender"`
	AddressLine1    pgtype.Text        `json:"address_line1"`
	AddressLine2    pgtype.Text        `json:"address_line2"`
	City            pgtype.Text        `json:"city"`
	State           pgtype.Text        `json:"state"`
	PinCode         pgtype.Text        `json:"pin_code"`
	ProfileImageUrl pgtype.Text        `json:"profile_image_url"`
	Notes           pgtype.Text        `json:"notes"`
	TotalSpent      pgtype.Numeric     `json:"total_spent"`
	OutstandingDues pgtype.Numeric     `json:"outstanding_dues"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CustomerNote struct {
	ID         int64              `json:"id"`
	CustomerID int64              `json:"customer_id"`
	UserID     pgtype.Int8        `json:"user_id"`
	Note       string             `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Expense struct {
	ID          int64              `json:"id"`
	ShopID      int64              `json:"shop_id"`
	CategoryID  pgtype.Int8        `json:"category_id"`
	Title       string             `json:"title"`
	Amount      pgtype.Numeric     `json:"amount"`
	ExpenseDate pgtype.Date        `json:"expense_date"`
	PaymentMode string             `json:"payment_mode"`
	ExpenseType string             `json:"expense_type"`
	Recurrence  pgtype.Text        `json:"recurrence"`
	ReceiptUrl  pgtype.Text        `json:"receipt_url"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedBy   pgtype.Int8        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ExpenseCategory struct {
	ID        int64              `json:"id"`
	ShopID    int64              `json:"shop_id"`
	Name      string             `json:"name"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EyeTest struct {
	ID              int64              `json:"id"`
	ShopID          int64              `json:"shop_id"`
	CustomerID      int64              `json:"customer_id"`
	TestedBy        pgtype.Int8        `json:"tested_by"`
	TestNumber      string             `json:"test_number"`
	TestDate        pgtype.Timestamptz `json:"test_date"`
	CheckupByType   pgtype.Text        `json:"checkup_by_type"`
	DoctorName      pgtype.Text        `json:"doctor_name"`
	HospitalName    pgtype.Text        `json:"hospital_name"`
	DoctorCity      pgtype.Text        `json:"doctor_city"`
	OpticalShopName pgtype.Text        `json:"optical_shop_name"`
	OpticalCity     pgtype.Text        `json:"optical_city"`
	ExaminerName    pgtype.Text        `json:"examiner_name"`
	ReSph           pgtype.Numeric     `json:"re_sph"`
	ReCyl           pgtype.Numeric     `json:"re_cyl"`
	ReAxis          pgtype.Int4        `json:"re_axis"`
	ReAdd           pgtype.Numeric     `json:"re_add"`
	RePd            pgtype.Numeric     `json:"re_pd"`
	RePrism         pgtype.Numeric     `json:"re_prism"`
	RePrismBase     pgtype.Text        `json:"re_prism_base"`
	ReVisualAcuity  pgtype.Text        `json:"re_visual_acuity"`
	LeSph           pgtype.Numeric     `json:"le_sph"`
	LeCyl           pgtype.Numeric     `json:"le_cyl"`
	LeAxis          pgtype.Int4        `json:"le_axis"`
	LeAdd           pgtype.Numeric     `json:"le_add"`
	LePd            pgtype.Numeric     `json:"le_pd"`
	LePrism         pgtype.Numeric     `json:"le_prism"`
	LePrismBase     pgtype.Text        `json:"le_prism_base"`
	LeVisualAcuity  pgtype.Text        `json:"le_visual_acuity"`
	TotalPd         pgtype.Numeric     `json:"total_pd"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Order struct {
	ID               int64              `json:"id"`
	ShopID           int64              `json:"shop_id"`
	CustomerID       int64              `json:"customer_id"`
	CreatedBy        pgtype.Int8        `json:"created_by"`
	OrderNumber      string             `json:"order_number"`
	OrderType        string             `json:"order_type"`
	Status           string             `json:"status"`
	PaymentStatus    string             `json:"payment_status"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	DiscountType     pgtype.Text        `json:"discount_type"`
	DiscountValue    pgtype.Numeric     `json:"discount_value"`
	DiscountAmount   pgtype.Numeric     `json:"discount_amount"`
	TaxableAmount    pgtype.Numeric     `json:"taxable_amount"`
	CgstAmount       pgtype.Numeric     `json:"cgst_amount"`
	SgstAmount       pgtype.Numeric     `json:"sgst_amount"`
	IgstAmount       pgtype.Numeric     `json:"igst_amount"`
	TotalTax         pgtype.Numeric     `json:"total_tax"`
	GrandTotal       pgtype.Numeric     `json:"grand_total"`
	AmountPaid       pgtype.Numeric     `json:"amount_paid"`
	BalanceDue       pgtype.Numeric     `json:"balance_due"`
	ExpectedDelivery pgtype.Date        `json:"expected_delivery"`
	DeliveredAt      pgtype.Timestamptz `json:"delivered_at"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID             int64              `json:"id"`
	OrderID        int64              `json:"order_id"`
	ProductID      pgtype.Int8        `json:"product_id"`
	ItemType       string             `json:"item_type"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Quantity       int32              `json:"quantity"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	DiscountAmount pgtype.Numeric     `json:"discount_amount"`
	TaxRate        pgtype.Numeric     `json:"tax_rate"`
	TaxAmount      pgtype.Numeric     `json:"tax_amount"`
	TotalPrice     pgtype.Numeric     `json:"total_price"`
	HsnCode        pgtype.Text        `json:"hsn_code"`
	Details        []byte             `json:"details"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OrderPayment struct {
	ID             int64              `json:"id"`
	OrderID        int64              `json:"order_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	PaymentMode    string             `json:"payment_mode"`
	TransactionRef pgtype.Text        `json:"transaction_ref"`
	PaymentDate    pgtype.Timestamptz `json:"payment_date"`
	Notes          pgtype.Text        `json:"notes"`
	ReceivedBy     pgtype.Int8        `json:"received_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OrderPrescription struct {
	ID                    int64              `json:"id"`
	OrderID               int64              `json:"order_id"`
	EyeTestID             pgtype.Int8        `json:"eye_test_id"`
	CheckupByType         pgtype.Text        `json:"checkup_by_type"`
	DoctorName            pgtype.Text        `json:"doctor_name"`
	HospitalName          pgtype.Text        `json:"hospital_name"`
	DoctorCity            pgtype.Text        `json:"doctor_city"`
	OpticalShopName       pgtype.Text        `json:"optical_shop_name"`
	OpticalCity           pgtype.Text        `json:"optical_city"`
	ExaminerName          pgtype.Text        `json:"examiner_name"`
	CheckupDate           pgtype.Date        `json:"checkup_date"`
	ReSph                 pgtype.Numeric     `json:"re_sph"`
	ReCyl                 pgtype.Numeric     `json:"re_cyl"`
	ReAxis                pgtype.Int4        `json:"re_axis"`
	ReAdd                 pgtype.Numeric     `json:"re_add"`
	RePd                  pgtype.Numeric     `json:"re_pd"`
	RePrism               pgtype.Numeric     `json:"re_prism"`
	RePrismBase           pgtype.Text        `json:"re_prism_base"`
	ReVisualAcuity        pgtype.Text        `json:"re_visual_acuity"`
	LeSph                 pgtype.Numeric     `json:"le_sph"`
	LeCyl                 pgtype.Numeric     `json:"le_cyl"`
	LeAxis                pgtype.Int4        `json:"le_axis"`
	LeAdd                 pgtype.Numeric     `json:"le_add"`
	LePd                  pgtype.Numeric     `json:"le_pd"`
	LePrism               pgtype.Numeric     `json:"le_prism"`
	LePrismBase           pgtype.Text        `json:"le_prism_base"`
	LeVisualAcuity        pgtype.Text        `json:"le_visual_acuity"`
	TotalPd               pgtype.Numeric     `json:"total_pd"`
	LensFor               pgtype.Text        `json:"lens_for"`
	LensType              pgtype.Text        `json:"lens_type"`
	LensMaterial          pgtype.Text        `json:"lens_material"`
	LensCoating           pgtype.Text        `json:"lens_coating"`
	LensSide              pgtype.Text        `json:"lens_side"`
	LensCompany           pgtype.Text        `json:"lens_company"`
	LensProduct           pgtype.Text        `json:"lens_product"`
	LensIndex             pgtype.Text        `json:"lens_index"`
	LensDia               pgtype.Text        `json:"lens_dia"`
	Tint                  pgtype.Text        `json:"tint"`
	ClBaseCurve           pgtype.Numeric     `json:"cl_base_curve"`
	ClDiameter            pgtype.Numeric     `json:"cl_diameter"`
	ClReplacementSchedule pgtype.Text        `json:"cl_replacement_schedule"`
	Notes                 pgtype.Text        `json:"notes"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type OrderStatusHistory struct {
	ID         int64              `json:"id"`
	OrderID    int64              `json:"order_id"`
	FromStatus pgtype.Text        `json:"from_status"`
	ToStatus   string             `json:"to_status"`
	ChangedBy  pgtype.Int8        `json:"changed_by"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID                    int64              `json:"id"`
	ShopID                int64              `json:"shop_id"`
	Name                  string             `json:"name"`
	Sku                   pgtype.Text        `json:"sku"`
	Category              string             `json:"category"`
	Brand                 pgtype.Text        `json:"brand"`
	Model                 pgtype.Text        `json:"model"`
	Color                 pgtype.Text        `json:"color"`
	Size                  pgtype.Text        `json:"size"`
	Description           pgtype.Text        `json:"description"`
	PurchasePrice         pgtype.Numeric     `json:"purchase_price"`
	SellingPrice          pgtype.Numeric     `json:"selling_price"`
	HsnCode               pgtype.Text        `json:"hsn_code"`
	GstRate               pgtype.Numeric     `json:"gst_rate"`
	CurrentStock          int32              `json:"current_stock"`
	MinStockLevel         int32              `json:"min_stock_level"`
	Barcode               pgtype.Text        `json:"barcode"`
	ImageUrl              pgtype.Text        `json:"image_url"`
	IsActive              bool               `json:"is_active"`
	FrameType             pgtype.Text        `json:"frame_type"`
	FrameMaterial         pgtype.Text        `json:"frame_material"`
	FrameShape            pgtype.Text        `json:"frame_shape"`
	TempleLength          pgtype.Numeric     `json:"temple_length"`
	BridgeWidth           pgtype.Numeric     `json:"bridge_width"`
	LensWidth             pgtype.Numeric     `json:"lens_width"`
	GenderTarget          pgtype.Text        `json:"gender_target"`
	ClReplacementSchedule pgtype.Text        `json:"cl_replacement_schedule"`
	ClBaseCurve           pgtype.Numeric     `json:"cl_base_curve"`
	ClDiameter            pgtype.Numeric     `json:"cl_diameter"`
	ClWaterContent        pgtype.Text        `json:"cl_water_content"`
	ClMaterial            pgtype.Text        `json:"cl_material"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ProductImage struct {
	ID        int64              `json:"id"`
	ProductID int64              `json:"product_id"`
	ImageUrl  string             `json:"image_url"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PurchaseBill struct {
	ID          int64              `json:"id"`
	ShopID      int64              `json:"shop_id"`
	VendorID    int64              `json:"vendor_id"`
	BillNumber  string             `json:"bill_number"`
	BillDate    pgtype.Date        `json:"bill_date"`
	DueDate     pgtype.Date        `json:"due_date"`
	Subtotal    pgtype.Numeric     `json:"subtotal"`
	TaxAmount   pgtype.Numeric     `json:"tax_amount"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	AmountPaid  pgtype.Numeric     `json:"amount_paid"`
	Balance     pgtype.Numeric     `json:"balance"`
	Status      string             `json:"status"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedBy   pgtype.Int8        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PurchaseBillItem struct {
	ID             int64              `json:"id"`
	PurchaseBillID int64              `json:"purchase_bill_id"`
	ProductID      pgtype.Int8        `json:"product_id"`
	Name           string             `json:"name"`
	Quantity       int32              `json:"quantity"`
	UnitPrice      pgtype.Numeric     `json:"unit_price"`
	TaxRate        pgtype.Numeric     `json:"tax_rate"`
	TaxAmount      pgtype.Numeric     `json:"tax_amount"`
	TotalPrice     pgtype.Numeric     `json:"total_price"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Repair struct {
	ID                 int64              `json:"id"`
	ShopID             int64              `json:"shop_id"`
	CustomerID         pgtype.Int8        `json:"customer_id"`
	RepairNumber       string             `json:"repair_number"`
	CustomerName       string             `json:"customer_name"`
	CustomerPhone      pgtype.Text        `json:"customer_phone"`
	CustomerCity       pgtype.Text        `json:"customer_city"`
	RepairType         string             `json:"repair_type"`
	ItemDescription    pgtype.Text        `json:"item_description"`
	ProblemDescription pgtype.Text        `json:"problem_description"`
	Status             string             `json:"status"`
	TotalAmount        pgtype.Numeric     `json:"total_amount"`
	AdvancePaid        pgtype.Numeric     `json:"advance_paid"`
	BalanceDue         pgtype.Numeric     `json:"balance_due"`
	PaymentMode        string             `json:"payment_mode"`
	ReceivedDate       pgtype.Timestamptz `json:"received_date"`
	ExpectedDelivery   pgtype.Date        `json:"expected_delivery"`
	DeliveredAt        pgtype.Timestamptz `json:"delivered_at"`
	TechnicianName     pgtype.Text        `json:"technician_name"`
	Notes              pgtype.Text        `json:"notes"`
	CreatedBy          pgtype.Int8        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Shop struct {
	ID                 int64              `json:"id"`
	Name               string             `json:"name"`
	Phone              pgtype.Text        `json:"phone"`
	Email              pgtype.Text        `json:"email"`
	AddressLine1       pgtype.Text        `json:"address_line1"`
	AddressLine2       pgtype.Text        `json:"address_line2"`
	City               pgtype.Text        `json:"city"`
	State              pgtype.Text        `json:"state"`
	PinCode            pgtype.Text        `json:"pin_code"`
	Gstin              pgtype.Text        `json:"gstin"`
	LogoUrl            pgtype.Text        `json:"logo_url"`
	InvoicePrefix      pgtype.Text        `json:"invoice_prefix"`
	InvoiceNextNumber  pgtype.Int8        `json:"invoice_next_number"`
	OrderPrefix        pgtype.Text        `json:"order_prefix"`
	OrderNextNumber    pgtype.Int8        `json:"order_next_number"`
	CurrencySymbol     pgtype.Text        `json:"currency_symbol"`
	DefaultTaxRate     pgtype.Numeric     `json:"default_tax_rate"`
	OptometristName    pgtype.Text        `json:"optometrist_name"`
	EyeTestingFee      pgtype.Numeric     `json:"eye_testing_fee"`
	TermsAndConditions pgtype.Text        `json:"terms_and_conditions"`
	Language           pgtype.Text        `json:"language"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type ShopSetting struct {
	ID           int64              `json:"id"`
	ShopID       int64              `json:"shop_id"`
	SettingKey   string             `json:"setting_key"`
	SettingValue pgtype.Text        `json:"setting_value"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type StockMovement struct {
	ID            int64              `json:"id"`
	ShopID        int64              `json:"shop_id"`
	ProductID     int64              `json:"product_id"`
	MovementType  string             `json:"movement_type"`
	Quantity      int32              `json:"quantity"`
	ReferenceType pgtype.Text        `json:"reference_type"`
	ReferenceID   pgtype.Int8        `json:"reference_id"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type TranslationCache struct {
	ID             int64              `json:"id"`
	SourceText     string             `json:"source_text"`
	SourceLang     string             `json:"source_lang"`
	TargetLang     string             `json:"target_lang"`
	TranslatedText string             `json:"translated_text"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID              int64              `json:"id"`
	ShopID          int64              `json:"shop_id"`
	Username        string             `json:"username"`
	Password        string             `json:"password"`
	FullName        string             `json:"full_name"`
	Email           pgtype.Text        `json:"email"`
	Phone           pgtype.Text        `json:"phone"`
	Role            string             `json:"role"`
	ProfileImageUrl pgtype.Text        `json:"profile_image_url"`
	IsActive        bool               `json:"is_active"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Vendor struct {
	ID                 int64              `json:"id"`
	ShopID             int64              `json:"shop_id"`
	Name               string             `json:"name"`
	ContactPerson      pgtype.Text        `json:"contact_person"`
	Phone              pgtype.Text        `json:"phone"`
	Email              pgtype.Text        `json:"email"`
	Gstin              pgtype.Text        `json:"gstin"`
	Address            pgtype.Text        `json:"address"`
	City               pgtype.Text        `json:"city"`
	State              pgtype.Text        `json:"state"`
	PinCode            pgtype.Text        `json:"pin_code"`
	Notes              pgtype.Text        `json:"notes"`
	OutstandingBalance pgtype.Numeric     `json:"outstanding_balance"`
	IsActive           bool               `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type VendorPayment struct {
	ID             int64              `json:"id"`
	ShopID         int64              `json:"shop_id"`
	VendorID       int64              `json:"vendor_id"`
	PurchaseBillID pgtype.Int8        `json:"purchase_bill_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	PaymentMode    string             `json:"payment_mode"`
	TransactionRef pgtype.Text        `json:"transaction_ref"`
	PaymentDate    pgtype.Timestamptz `json:"payment_date"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
