// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_payments.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderPayment = `-- name: CreateOrderPayment :one
INSERT INTO order_payments (
    order_id, amount, payment_mode, transaction_ref, notes, received_by
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, order_id, amount, payment_mode, transaction_ref, payment_date, notes, received_by, created_at
`

type CreateOrderPaymentParams struct {
	OrderID        int64          `json:"order_id"`
	Amount         pgtype.Numeric `json:"amount"`
	PaymentMode    string         `json:"payment_mode"`
	TransactionRef pgtype.Text    `json:"transaction_ref"`
	Notes          pgtype.Text    `json:"notes"`
	ReceivedBy     pgtype.Int8    `json:"received_by"`
}

func (q *Queries) CreateOrderPayment(ctx context.Context, arg CreateOrderPaymentParams) (OrderPayment, error) {
	row := q.db.QueryRow(ctx, createOrderPayment,
		arg.OrderID,
		arg.Amount,
		arg.PaymentMode,
		arg.TransactionRef,
		arg.Notes,
		arg.ReceivedBy,
	)
	var i OrderPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.PaymentMode,
		&i.TransactionRef,
		&i.PaymentDate,
		&i.Notes,
		&i.ReceivedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalPaidForOrder = `-- name: GetTotalPaidForOrder :one
SELECT COALESCE(SUM(amount), 0)::decimal(12,2)
FROM order_payments
WHERE order_id = $1
`

func (q *Queries) GetTotalPaidForOrder(ctx context.Context, orderID int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalPaidForOrder, orderID)
	var column_1 pgtype.Numeric
	err := row.Scan(&column_1)
	return column_1, err
}

const listOrderPayments = `-- name: ListOrderPayments :many
SELECT op.id, op.order_id, op.amount, op.payment_mode, op.transaction_ref, op.payment_date, op.notes, op.received_by, op.created_at, u.full_name as received_by_name
FROM order_payments op
LEFT JOIN users u ON op.received_by = u.id
WHERE op.order_id = $1
ORDER BY op.payment_date ASC, op.id ASC
`

type ListOrderPaymentsRow struct {
	ID             int64              `json:"id"`
	OrderID        int64              `json:"order_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	PaymentMode    string             `json:"payment_mode"`
	TransactionRef pgtype.Text        `json:"transaction_ref"`
	PaymentDate    pgtype.Timestamptz `json:"payment_date"`
	Notes          pgtype.Text        `json:"notes"`
	ReceivedBy     pgtype.Int8        `json:"received_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ReceivedByName pgtype.Text        `json:"received_by_name"`
}

func (q *Queries) ListOrderPayments(ctx context.Context, orderID int64) ([]ListOrderPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listOrderPayments, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderPaymentsRow{}
	for rows.Next() {
		var i ListOrderPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Amount,
			&i.PaymentMode,
			&i.TransactionRef,
			&i.PaymentDate,
			&i.Notes,
			&i.ReceivedBy,
			&i.CreatedAt,
			&i.ReceivedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
