// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_prescriptions.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderPrescription = `-- name: CreateOrderPrescription :one
INSERT INTO order_prescriptions (
    order_id, eye_test_id,
    checkup_by_type, doctor_name, hospital_name, doctor_city,
    optical_shop_name, optical_city, examiner_name, checkup_date,
    re_sph, re_cyl, re_axis, re_add, re_pd, re_prism, re_prism_base, re_visual_acuity,
    le_sph, le_cyl, le_axis, le_add, le_pd, le_prism, le_prism_base, le_visual_acuity,
    total_pd, lens_for, lens_type, lens_material, lens_coating, lens_side,
    lens_company, lens_product, lens_index, lens_dia,
    tint, cl_base_curve, cl_diameter, cl_replacement_schedule, notes
) VALUES (
    $1, $2,
    $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22, $23, $24, $25, $26,
    $27, $28, $29, $30, $31, $32,
    $33, $34, $35, $36,
    $37, $38, $39, $40, $41
)
RETURNING id, order_id, eye_test_id, checkup_by_type, doctor_name, hospital_name, doctor_city, optical_shop_name, optical_city, examiner_name, checkup_date, re_sph, re_cyl, re_axis, re_add, re_pd, re_prism, re_prism_base, re_visual_acuity, le_sph, le_cyl, le_axis, le_add, le_pd, le_prism, le_prism_base, le_visual_acuity, total_pd, lens_for, lens_type, lens_material, lens_coating, lens_side, lens_company, lens_product, lens_index, lens_dia, tint, cl_base_curve, cl_diameter, cl_replacement_schedule, notes, created_at
`

type CreateOrderPrescriptionParams struct {
	OrderID               int64          `json:"order_id"`
	EyeTestID             pgtype.Int8    `json:"eye_test_id"`
	CheckupByType         pgtype.Text    `json:"checkup_by_type"`
	DoctorName            pgtype.Text    `json:"doctor_name"`
	HospitalName          pgtype.Text    `json:"hospital_name"`
	DoctorCity            pgtype.Text    `json:"doctor_city"`
	OpticalShopName       pgtype.Text    `json:"optical_shop_name"`
	OpticalCity           pgtype.Text    `json:"optical_city"`
	ExaminerName          pgtype.Text    `json:"examiner_name"`
	CheckupDate           pgtype.Date    `json:"checkup_date"`
	ReSph                 pgtype.Numeric `json:"re_sph"`
	ReCyl                 pgtype.Numeric `json:"re_cyl"`
	ReAxis                pgtype.Int4    `json:"re_axis"`
	ReAdd                 pgtype.Numeric `json:"re_add"`
	RePd                  pgtype.Numeric `json:"re_pd"`
	RePrism               pgtype.Numeric `json:"re_prism"`
	RePrismBase           pgtype.Text    `json:"re_prism_base"`
	ReVisualAcuity        pgtype.Text    `json:"re_visual_acuity"`
	LeSph                 pgtype.Numeric `json:"le_sph"`
	LeCyl                 pgtype.Numeric `json:"le_cyl"`
	LeAxis                pgtype.Int4    `json:"le_axis"`
	LeAdd                 pgtype.Numeric `json:"le_add"`
	LePd                  pgtype.Numeric `json:"le_pd"`
	LePrism               pgtype.Numeric `json:"le_prism"`
	LePrismBase           pgtype.Text    `json:"le_prism_base"`
	LeVisualAcuity        pgtype.Text    `json:"le_visual_acuity"`
	TotalPd               pgtype.Numeric `json:"total_pd"`
	LensFor               pgtype.Text    `json:"lens_for"`
	LensType              pgtype.Text    `json:"lens_type"`
	LensMaterial          pgtype.Text    `json:"lens_material"`
	LensCoating           pgtype.Text    `json:"lens_coating"`
	LensSide              pgtype.Text    `json:"lens_side"`
	LensCompany           pgtype.Text    `json:"lens_company"`
	LensProduct           pgtype.Text    `json:"lens_product"`
	LensIndex             pgtype.Text    `json:"lens_index"`
	LensDia               pgtype.Text    `json:"lens_dia"`
	Tint                  pgtype.Text    `json:"tint"`
	ClBaseCurve           pgtype.Numeric `json:"cl_base_curve"`
	ClDiameter            pgtype.Numeric `json:"cl_diameter"`
	ClReplacementSchedule pgtype.Text    `json:"cl_replacement_schedule"`
	Notes                 pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateOrderPrescription(ctx context.Context, arg CreateOrderPrescriptionParams) (OrderPrescription, error) {
	row := q.db.QueryRow(ctx, createOrderPrescription,
		arg.OrderID,
		arg.EyeTestID,
		arg.CheckupByType,
		arg.DoctorName,
		arg.HospitalName,
		arg.DoctorCity,
		arg.OpticalShopName,
		arg.OpticalCity,
		arg.ExaminerName,
		arg.CheckupDate,
		arg.ReSph,
		arg.ReCyl,
		arg.ReAxis,
		arg.ReAdd,
		arg.RePd,
		arg.RePrism,
		arg.RePrismBase,
		arg.ReVisualAcuity,
		arg.LeSph,
		arg.LeCyl,
		arg.LeAxis,
		arg.LeAdd,
		arg.LePd,
		arg.LePrism,
		arg.LePrismBase,
		arg.LeVisualAcuity,
		arg.TotalPd,
		arg.LensFor,
		arg.LensType,
		arg.LensMaterial,
		arg.LensCoating,
		arg.LensSide,
		arg.LensCompany,
		arg.LensProduct,
		arg.LensIndex,
		arg.LensDia,
		arg.Tint,
		arg.ClBaseCurve,
		arg.ClDiameter,
		arg.ClReplacementSchedule,
		arg.Notes,
	)
	var i OrderPrescription
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.EyeTestID,
		&i.CheckupByType,
		&i.DoctorName,
		&i.HospitalName,
		&i.DoctorCity,
		&i.OpticalShopName,
		&i.OpticalCity,
		&i.ExaminerName,
		&i.CheckupDate,
		&i.ReSph,
		&i.ReCyl,
		&i.ReAxis,
		&i.ReAdd,
		&i.RePd,
		&i.RePrism,
		&i.RePrismBase,
		&i.ReVisualAcuity,
		&i.LeSph,
		&i.LeCyl,
		&i.LeAxis,
		&i.LeAdd,
		&i.LePd,
		&i.LePrism,
		&i.LePrismBase,
		&i.LeVisualAcuity,
		&i.TotalPd,
		&i.LensFor,
		&i.LensType,
		&i.LensMaterial,
		&i.LensCoating,
		&i.LensSide,
		&i.LensCompany,
		&i.LensProduct,
		&i.LensIndex,
		&i.LensDia,
		&i.Tint,
		&i.ClBaseCurve,
		&i.ClDiameter,
		&i.ClReplacementSchedule,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrderPrescription = `-- name: DeleteOrderPrescription :exec
DELETE FROM order_prescriptions
WHERE order_id = $1
`

func (q *Queries) DeleteOrderPrescription(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, deleteOrderPrescription, orderID)
	return err
}

const getOrderPrescription = `-- name: GetOrderPrescription :one
SELECT id, order_id, eye_test_id, checkup_by_type, doctor_name, hospital_name, doctor_city, optical_shop_name, optical_city, examiner_name, checkup_date, re_sph, re_cyl, re_axis, re_add, re_pd, re_prism, re_prism_base, re_visual_acuity, le_sph, le_cyl, le_axis, le_add, le_pd, le_prism, le_prism_base, le_visual_acuity, total_pd, lens_for, lens_type, lens_material, lens_coating, lens_side, lens_company, lens_product, lens_index, lens_dia, tint, cl_base_curve, cl_diameter, cl_replacement_schedule, notes, created_at FROM order_prescriptions
WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetOrderPrescription(ctx context.Context, orderID int64) (OrderPrescription, error) {
	row := q.db.QueryRow(ctx, getOrderPrescription, orderID)
	var i OrderPrescription
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.EyeTestID,
		&i.CheckupByType,
		&i.DoctorName,
		&i.HospitalName,
		&i.DoctorCity,
		&i.OpticalShopName,
		&i.OpticalCity,
		&i.ExaminerName,
		&i.CheckupDate,
		&i.ReSph,
		&i.ReCyl,
		&i.ReAxis,
		&i.ReAdd,
		&i.RePd,
		&i.RePrism,
		&i.RePrismBase,
		&i.ReVisualAcuity,
		&i.LeSph,
		&i.LeCyl,
		&i.LeAxis,
		&i.LeAdd,
		&i.LePd,
		&i.LePrism,
		&i.LePrismBase,
		&i.LeVisualAcuity,
		&i.TotalPd,
		&i.LensFor,
		&i.LensType,
		&i.LensMaterial,
		&i.LensCoating,
		&i.LensSide,
		&i.LensCompany,
		&i.LensProduct,
		&i.LensIndex,
		&i.LensDia,
		&i.Tint,
		&i.ClBaseCurve,
		&i.ClDiameter,
		&i.ClReplacementSchedule,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
