// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id, product_id, item_type, name, description,
    quantity, unit_price, discount_amount, tax_rate, tax_amount, total_price, hsn_code, details
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, order_id, product_id, item_type, name, description, quantity, unit_price, discount_amount, tax_rate, tax_amount, total_price, hsn_code, details, created_at
`

type CreateOrderItemParams struct {
	OrderID        int64          `json:"order_id"`
	ProductID      pgtype.Int8    `json:"product_id"`
	ItemType       string         `json:"item_type"`
	Name           string         `json:"name"`
	Description    pgtype.Text    `json:"description"`
	Quantity       int32          `json:"quantity"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	DiscountAmount pgtype.Numeric `json:"discount_amount"`
	TaxRate        pgtype.Numeric `json:"tax_rate"`
	TaxAmount      pgtype.Numeric `json:"tax_amount"`
	TotalPrice     pgtype.Numeric `json:"total_price"`
	HsnCode        pgtype.Text    `json:"hsn_code"`
	Details        []byte         `json:"details"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ItemType,
		arg.Name,
		arg.Description,
		arg.Quantity,
		arg.UnitPrice,
		arg.DiscountAmount,
		arg.TaxRate,
		arg.TaxAmount,
		arg.TotalPrice,
		arg.HsnCode,
		arg.Details,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ItemType,
		&i.Name,
		&i.Description,
		&i.Quantity,
		&i.UnitPrice,
		&i.DiscountAmount,
		&i.TaxRate,
		&i.TaxAmount,
		&i.TotalPrice,
		&i.HsnCode,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrderItems = `-- name: DeleteOrderItems :exec
DELETE FROM order_items
WHERE order_id = $1
`

func (q *Queries) DeleteOrderItems(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, deleteOrderItems, orderID)
	return err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, product_id, item_type, name, description, quantity, unit_price, discount_amount, tax_rate, tax_amount, total_price, hsn_code, details, created_at FROM order_items
WHERE order_id = $1
ORDER BY id ASC
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ItemType,
			&i.Name,
			&i.Description,
			&i.Quantity,
			&i.UnitPrice,
			&i.DiscountAmount,
			&i.TaxRate,
			&i.TaxAmount,
			&i.TotalPrice,
			&i.HsnCode,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
