// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_status_history.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderStatusHistory = `-- name: CreateOrderStatusHistory :one
INSERT INTO order_status_history (
    order_id, from_status, to_status, changed_by, notes
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, order_id, from_status, to_status, changed_by, notes, created_at
`

type CreateOrderStatusHistoryParams struct {
	OrderID    int64       `json:"order_id"`
	FromStatus pgtype.Text `json:"from_status"`
	ToStatus   string      `json:"to_status"`
	ChangedBy  pgtype.Int8 `json:"changed_by"`
	Notes      pgtype.Text `json:"notes"`
}

func (q *Queries) CreateOrderStatusHistory(ctx context.Context, arg CreateOrderStatusHistoryParams) (OrderStatusHistory, error) {
	row := q.db.QueryRow(ctx, createOrderStatusHistory,
		arg.OrderID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedBy,
		arg.Notes,
	)
	var i OrderStatusHistory
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ChangedBy,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderStatusHistory = `-- name: ListOrderStatusHistory :many
SELECT osh.id, osh.order_id, osh.from_status, osh.to_status, osh.changed_by, osh.notes, osh.created_at, u.full_name as changed_by_name
FROM order_status_history osh
LEFT JOIN users u ON osh.changed_by = u.id
WHERE osh.order_id = $1
ORDER BY osh.created_at ASC
`

type ListOrderStatusHistoryRow struct {
	ID            int64              `json:"id"`
	OrderID       int64              `json:"order_id"`
	FromStatus    pgtype.Text        `json:"from_status"`
	ToStatus      string             `json:"to_status"`
	ChangedBy     pgtype.Int8        `json:"changed_by"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ChangedByName pgtype.Text        `json:"changed_by_name"`
}

func (q *Queries) ListOrderStatusHistory(ctx context.Context, orderID int64) ([]ListOrderStatusHistoryRow, error) {
	rows, err := q.db.Query(ctx, listOrderStatusHistory, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderStatusHistoryRow{}
	for rows.Next() {
		var i ListOrderStatusHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ChangedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.ChangedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
