// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelOrder = `-- name: CancelOrder :one
UPDATE orders
SET status = 'cancelled', updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, customer_id, created_by, order_number, order_type, status, payment_status, subtotal, discount_type, discount_value, discount_amount, taxable_amount, cgst_amount, sgst_amount, igst_amount, total_tax, grand_total, amount_paid, balance_due, expected_delivery, delivered_at, notes, created_at, updated_at
`

type CancelOrderParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, cancelOrder, arg.ID, arg.ShopID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.CreatedBy,
		&i.OrderNumber,
		&i.OrderType,
		&i.Status,
		&i.PaymentStatus,
		&i.Subtotal,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.TaxableAmount,
		&i.CgstAmount,
		&i.SgstAmount,
		&i.IgstAmount,
		&i.TotalTax,
		&i.GrandTotal,
		&i.AmountPaid,
		&i.BalanceDue,
		&i.ExpectedDelivery,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*)
FROM orders o
JOIN customers c ON o.customer_id = c.id
WHERE o.shop_id = $1
  AND (
    $2::text = '' OR
    o.order_number ILIKE '%' || $2 || '%' OR
    c.first_name ILIKE '%' || $2 || '%' OR
    c.last_name ILIKE '%' || $2 || '%' OR
    c.phone ILIKE '%' || $2 || '%'
  )
  AND ($3::text = 'all' OR o.status = $3)
  AND ($4::text = 'all' OR o.payment_status = $4)
  AND ($5::text = 'all' OR o.order_type = $5)
  AND ($6::timestamptz IS NULL OR o.created_at >= $6)
  AND ($7::timestamptz IS NULL OR o.created_at <= $7)
`

type CountOrdersParams struct {
	ShopID        int64              `json:"shop_id"`
	Search        string             `json:"search"`
	Status        string             `json:"status"`
	PaymentStatus string             `json:"payment_status"`
	OrderType     string             `json:"order_type"`
	FromDate      pgtype.Timestamptz `json:"from_date"`
	ToDate        pgtype.Timestamptz `json:"to_date"`
}

func (q *Queries) CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders,
		arg.ShopID,
		arg.Search,
		arg.Status,
		arg.PaymentStatus,
		arg.OrderType,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    shop_id, customer_id, created_by, order_number, order_type, status,
    payment_status, subtotal, discount_type, discount_value, discount_amount,
    taxable_amount, cgst_amount, sgst_amount, igst_amount, total_tax,
    grand_total, amount_paid, balance_due, expected_delivery, notes
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21
)
RETURNING id, shop_id, customer_id, created_by, order_number, order_type, status, payment_status, subtotal, discount_type, discount_value, discount_amount, taxable_amount, cgst_amount, sgst_amount, igst_amount, total_tax, grand_total, amount_paid, balance_due, expected_delivery, delivered_at, notes, created_at, updated_at
`

type CreateOrderParams struct {
	ShopID           int64          `json:"shop_id"`
	CustomerID       int64          `json:"customer_id"`
	CreatedBy        pgtype.Int8    `json:"created_by"`
	OrderNumber      string         `json:"order_number"`
	OrderType        string         `json:"order_type"`
	Status           string         `json:"status"`
	PaymentStatus    string         `json:"payment_status"`
	Subtotal         pgtype.Numeric `json:"subtotal"`
	DiscountType     pgtype.Text    `json:"discount_type"`
	DiscountValue    pgtype.Numeric `json:"discount_value"`
	DiscountAmount   pgtype.Numeric `json:"discount_amount"`
	TaxableAmount    pgtype.Numeric `json:"taxable_amount"`
	CgstAmount       pgtype.Numeric `json:"cgst_amount"`
	SgstAmount       pgtype.Numeric `json:"sgst_amount"`
	IgstAmount       pgtype.Numeric `json:"igst_amount"`
	TotalTax         pgtype.Numeric `json:"total_tax"`
	GrandTotal       pgtype.Numeric `json:"grand_total"`
	AmountPaid       pgtype.Numeric `json:"amount_paid"`
	BalanceDue       pgtype.Numeric `json:"balance_due"`
	ExpectedDelivery pgtype.Date    `json:"expected_delivery"`
	Notes            pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ShopID,
		arg.CustomerID,
		arg.CreatedBy,
		arg.OrderNumber,
		arg.OrderType,
		arg.Status,
		arg.PaymentStatus,
		arg.Subtotal,
		arg.DiscountType,
		arg.DiscountValue,
		arg.DiscountAmount,
		arg.TaxableAmount,
		arg.CgstAmount,
		arg.SgstAmount,
		arg.IgstAmount,
		arg.TotalTax,
		arg.GrandTotal,
		arg.AmountPaid,
		arg.BalanceDue,
		arg.ExpectedDelivery,
		arg.Notes,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.CreatedBy,
		&i.OrderNumber,
		&i.OrderType,
		&i.Status,
		&i.PaymentStatus,
		&i.Subtotal,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.TaxableAmount,
		&i.CgstAmount,
		&i.SgstAmount,
		&i.IgstAmount,
		&i.TotalTax,
		&i.GrandTotal,
		&i.AmountPaid,
		&i.BalanceDue,
		&i.ExpectedDelivery,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT o.id, o.shop_id, o.customer_id, o.created_by, o.order_number, o.order_type, o.status, o.payment_status, o.subtotal, o.discount_type, o.discount_value, o.discount_amount, o.taxable_amount, o.cgst_amount, o.sgst_amount, o.igst_amount, o.total_tax, o.grand_total, o.amount_paid, o.balance_due, o.expected_delivery, o.delivered_at, o.notes, o.created_at, o.updated_at, c.first_name, c.last_name, c.phone as customer_phone, c.city as customer_city, c.date_of_birth as customer_dob, c.gender as customer_gender, c.address_line1 as customer_address, u.full_name as created_by_name
FROM orders o
JOIN customers c ON o.customer_id = c.id
LEFT JOIN users u ON o.created_by = u.id
WHERE o.id = $1 AND o.shop_id = $2 LIMIT 1
`

type GetOrderByIDParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

type GetOrderByIDRow struct {
	ID               int64              `json:"id"`
	ShopID           int64              `json:"shop_id"`
	CustomerID       int64              `json:"customer_id"`
	CreatedBy        pgtype.Int8        `json:"created_by"`
	OrderNumber      string             `json:"order_number"`
	OrderType        string             `json:"order_type"`
	Status           string             `json:"status"`
	PaymentStatus    string             `json:"payment_status"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	DiscountType     pgtype.Text        `json:"discount_type"`
	DiscountValue    pgtype.Numeric     `json:"discount_value"`
	DiscountAmount   pgtype.Numeric     `json:"discount_amount"`
	TaxableAmount    pgtype.Numeric     `json:"taxable_amount"`
	CgstAmount       pgtype.Numeric     `json:"cgst_amount"`
	SgstAmount       pgtype.Numeric     `json:"sgst_amount"`
	IgstAmount       pgtype.Numeric     `json:"igst_amount"`
	TotalTax         pgtype.Numeric     `json:"total_tax"`
	GrandTotal       pgtype.Numeric     `json:"grand_total"`
	AmountPaid       pgtype.Numeric     `json:"amount_paid"`
	BalanceDue       pgtype.Numeric     `json:"balance_due"`
	ExpectedDelivery pgtype.Date        `json:"expected_delivery"`
	DeliveredAt      pgtype.Timestamptz `json:"delivered_at"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstName        string             `json:"first_name"`
	LastName         pgtype.Text        `json:"last_name"`
	CustomerPhone    pgtype.Text        `json:"customer_phone"`
	CustomerCity     pgtype.Text        `json:"customer_city"`
	CustomerDob      pgtype.Date        `json:"customer_dob"`
	CustomerGender   pgtype.Text        `json:"customer_gender"`
	CustomerAddress  pgtype.Text        `json:"customer_address"`
	CreatedByName    pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, arg.ID, arg.ShopID)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.CreatedBy,
		&i.OrderNumber,
		&i.OrderType,
		&i.Status,
		&i.PaymentStatus,
		&i.Subtotal,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.TaxableAmount,
		&i.CgstAmount,
		&i.SgstAmount,
		&i.IgstAmount,
		&i.TotalTax,
		&i.GrandTotal,
		&i.AmountPaid,
		&i.BalanceDue,
		&i.ExpectedDelivery,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.CustomerPhone,
		&i.CustomerCity,
		&i.CustomerDob,
		&i.CustomerGender,
		&i.CustomerAddress,
		&i.CreatedByName,
	)
	return i, err
}

const getOrderByNumber = `-- name: GetOrderByNumber :one
SELECT o.id, o.shop_id, o.customer_id, o.created_by, o.order_number, o.order_type, o.status, o.payment_status, o.subtotal, o.discount_type, o.discount_value, o.discount_amount, o.taxable_amount, o.cgst_amount, o.sgst_amount, o.igst_amount, o.total_tax, o.grand_total, o.amount_paid, o.balance_due, o.expected_delivery, o.delivered_at, o.notes, o.created_at, o.updated_at, c.first_name, c.last_name, c.phone as customer_phone, c.city as customer_city, c.date_of_birth as customer_dob, c.gender as customer_gender, c.address_line1 as customer_address, u.full_name as created_by_name
FROM orders o
JOIN customers c ON o.customer_id = c.id
LEFT JOIN users u ON o.created_by = u.id
WHERE o.order_number = $1 AND o.shop_id = $2 LIMIT 1
`

type GetOrderByNumberParams struct {
	OrderNumber string `json:"order_number"`
	ShopID      int64  `json:"shop_id"`
}

type GetOrderByNumberRow struct {
	ID               int64              `json:"id"`
	ShopID           int64              `json:"shop_id"`
	CustomerID       int64              `json:"customer_id"`
	CreatedBy        pgtype.Int8        `json:"created_by"`
	OrderNumber      string             `json:"order_number"`
	OrderType        string             `json:"order_type"`
	Status           string             `json:"status"`
	PaymentStatus    string             `json:"payment_status"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	DiscountType     pgtype.Text        `json:"discount_type"`
	DiscountValue    pgtype.Numeric     `json:"discount_value"`
	DiscountAmount   pgtype.Numeric     `json:"discount_amount"`
	TaxableAmount    pgtype.Numeric     `json:"taxable_amount"`
	CgstAmount       pgtype.Numeric     `json:"cgst_amount"`
	SgstAmount       pgtype.Numeric     `json:"sgst_amount"`
	IgstAmount       pgtype.Numeric     `json:"igst_amount"`
	TotalTax         pgtype.Numeric     `json:"total_tax"`
	GrandTotal       pgtype.Numeric     `json:"grand_total"`
	AmountPaid       pgtype.Numeric     `json:"amount_paid"`
	BalanceDue       pgtype.Numeric     `json:"balance_due"`
	ExpectedDelivery pgtype.Date        `json:"expected_delivery"`
	DeliveredAt      pgtype.Timestamptz `json:"delivered_at"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstName        string             `json:"first_name"`
	LastName         pgtype.Text        `json:"last_name"`
	CustomerPhone    pgtype.Text        `json:"customer_phone"`
	CustomerCity     pgtype.Text        `json:"customer_city"`
	CustomerDob      pgtype.Date        `json:"customer_dob"`
	CustomerGender   pgtype.Text        `json:"customer_gender"`
	CustomerAddress  pgtype.Text        `json:"customer_address"`
	CreatedByName    pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) GetOrderByNumber(ctx context.Context, arg GetOrderByNumberParams) (GetOrderByNumberRow, error) {
	row := q.db.QueryRow(ctx, getOrderByNumber, arg.OrderNumber, arg.ShopID)
	var i GetOrderByNumberRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.CreatedBy,
		&i.OrderNumber,
		&i.OrderType,
		&i.Status,
		&i.PaymentStatus,
		&i.Subtotal,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.TaxableAmount,
		&i.CgstAmount,
		&i.SgstAmount,
		&i.IgstAmount,
		&i.TotalTax,
		&i.GrandTotal,
		&i.AmountPaid,
		&i.BalanceDue,
		&i.ExpectedDelivery,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.CustomerPhone,
		&i.CustomerCity,
		&i.CustomerDob,
		&i.CustomerGender,
		&i.CustomerAddress,
		&i.CreatedByName,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT o.id, o.shop_id, o.customer_id, o.created_by, o.order_number, o.order_type, o.status, o.payment_status, o.subtotal, o.discount_type, o.discount_value, o.discount_amount, o.taxable_amount, o.cgst_amount, o.sgst_amount, o.igst_amount, o.total_tax, o.grand_total, o.amount_paid, o.balance_due, o.expected_delivery, o.delivered_at, o.notes, o.created_at, o.updated_at, c.first_name, c.last_name, c.phone as customer_phone, u.full_name as created_by_name
FROM orders o
JOIN customers c ON o.customer_id = c.id
LEFT JOIN users u ON o.created_by = u.id
WHERE o.shop_id = $1
  AND (
    $2::text = '' OR
    o.order_number ILIKE '%' || $2 || '%' OR
    c.first_name ILIKE '%' || $2 || '%' OR
    c.last_name ILIKE '%' || $2 || '%' OR
    c.phone ILIKE '%' || $2 || '%'
  )
  AND ($3::text = 'all' OR o.status = $3)
  AND ($4::text = 'all' OR o.payment_status = $4)
  AND ($5::text = 'all' OR o.order_type = $5)
  AND ($6::timestamptz IS NULL OR o.created_at >= $6)
  AND ($7::timestamptz IS NULL OR o.created_at <= $7)
ORDER BY o.created_at DESC
LIMIT $9 OFFSET $8
`

type ListOrdersParams struct {
	ShopID        int64              `json:"shop_id"`
	Search        string             `json:"search"`
	Status        string             `json:"status"`
	PaymentStatus string             `json:"payment_status"`
	OrderType     string             `json:"order_type"`
	FromDate      pgtype.Timestamptz `json:"from_date"`
	ToDate        pgtype.Timestamptz `json:"to_date"`
	OffsetCount   int32              `json:"offset_count"`
	LimitCount    int32              `json:"limit_count"`
}

type ListOrdersRow struct {
	ID               int64              `json:"id"`
	ShopID           int64              `json:"shop_id"`
	CustomerID       int64              `json:"customer_id"`
	CreatedBy        pgtype.Int8        `json:"created_by"`
	OrderNumber      string             `json:"order_number"`
	OrderType        string             `json:"order_type"`
	Status           string             `json:"status"`
	PaymentStatus    string             `json:"payment_status"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	DiscountType     pgtype.Text        `json:"discount_type"`
	DiscountValue    pgtype.Numeric     `json:"discount_value"`
	DiscountAmount   pgtype.Numeric     `json:"discount_amount"`
	TaxableAmount    pgtype.Numeric     `json:"taxable_amount"`
	CgstAmount       pgtype.Numeric     `json:"cgst_amount"`
	SgstAmount       pgtype.Numeric     `json:"sgst_amount"`
	IgstAmount       pgtype.Numeric     `json:"igst_amount"`
	TotalTax         pgtype.Numeric     `json:"total_tax"`
	GrandTotal       pgtype.Numeric     `json:"grand_total"`
	AmountPaid       pgtype.Numeric     `json:"amount_paid"`
	BalanceDue       pgtype.Numeric     `json:"balance_due"`
	ExpectedDelivery pgtype.Date        `json:"expected_delivery"`
	DeliveredAt      pgtype.Timestamptz `json:"delivered_at"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstName        string             `json:"first_name"`
	LastName         pgtype.Text        `json:"last_name"`
	CustomerPhone    pgtype.Text        `json:"customer_phone"`
	CreatedByName    pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.ShopID,
		arg.Search,
		arg.Status,
		arg.PaymentStatus,
		arg.OrderType,
		arg.FromDate,
		arg.ToDate,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersRow{}
	for rows.Next() {
		var i ListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CustomerID,
			&i.CreatedBy,
			&i.OrderNumber,
			&i.OrderType,
			&i.Status,
			&i.PaymentStatus,
			&i.Subtotal,
			&i.DiscountType,
			&i.DiscountValue,
			&i.DiscountAmount,
			&i.TaxableAmount,
			&i.CgstAmount,
			&i.SgstAmount,
			&i.IgstAmount,
			&i.TotalTax,
			&i.GrandTotal,
			&i.AmountPaid,
			&i.BalanceDue,
			&i.ExpectedDelivery,
			&i.DeliveredAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.CustomerPhone,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT o.id, o.shop_id, o.customer_id, o.created_by, o.order_number, o.order_type, o.status, o.payment_status, o.subtotal, o.discount_type, o.discount_value, o.discount_amount, o.taxable_amount, o.cgst_amount, o.sgst_amount, o.igst_amount, o.total_tax, o.grand_total, o.amount_paid, o.balance_due, o.expected_delivery, o.delivered_at, o.notes, o.created_at, o.updated_at, u.full_name as created_by_name
FROM orders o
LEFT JOIN users u ON o.created_by = u.id
WHERE o.customer_id = $1 AND o.shop_id = $2
ORDER BY o.created_at DESC
`

type ListOrdersByCustomerParams struct {
	CustomerID int64 `json:"customer_id"`
	ShopID     int64 `json:"shop_id"`
}

type ListOrdersByCustomerRow struct {
	ID               int64              `json:"id"`
	ShopID           int64              `json:"shop_id"`
	CustomerID       int64              `json:"customer_id"`
	CreatedBy        pgtype.Int8        `json:"created_by"`
	OrderNumber      string             `json:"order_number"`
	OrderType        string             `json:"order_type"`
	Status           string             `json:"status"`
	PaymentStatus    string             `json:"payment_status"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	DiscountType     pgtype.Text        `json:"discount_type"`
	DiscountValue    pgtype.Numeric     `json:"discount_value"`
	DiscountAmount   pgtype.Numeric     `json:"discount_amount"`
	TaxableAmount    pgtype.Numeric     `json:"taxable_amount"`
	CgstAmount       pgtype.Numeric     `json:"cgst_amount"`
	SgstAmount       pgtype.Numeric     `json:"sgst_amount"`
	IgstAmount       pgtype.Numeric     `json:"igst_amount"`
	TotalTax         pgtype.Numeric     `json:"total_tax"`
	GrandTotal       pgtype.Numeric     `json:"grand_total"`
	AmountPaid       pgtype.Numeric     `json:"amount_paid"`
	BalanceDue       pgtype.Numeric     `json:"balance_due"`
	ExpectedDelivery pgtype.Date        `json:"expected_delivery"`
	DeliveredAt      pgtype.Timestamptz `json:"delivered_at"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CreatedByName    pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListOrdersByCustomer(ctx context.Context, arg ListOrdersByCustomerParams) ([]ListOrdersByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomer, arg.CustomerID, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersByCustomerRow{}
	for rows.Next() {
		var i ListOrdersByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CustomerID,
			&i.CreatedBy,
			&i.OrderNumber,
			&i.OrderType,
			&i.Status,
			&i.PaymentStatus,
			&i.Subtotal,
			&i.DiscountType,
			&i.DiscountValue,
			&i.DiscountAmount,
			&i.TaxableAmount,
			&i.CgstAmount,
			&i.SgstAmount,
			&i.IgstAmount,
			&i.TotalTax,
			&i.GrandTotal,
			&i.AmountPaid,
			&i.BalanceDue,
			&i.ExpectedDelivery,
			&i.DeliveredAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersDue = `-- name: ListOrdersDue :many
SELECT o.id, o.shop_id, o.customer_id, o.created_by, o.order_number, o.order_type, o.status, o.payment_status, o.subtotal, o.discount_type, o.discount_value, o.discount_amount, o.taxable_amount, o.cgst_amount, o.sgst_amount, o.igst_amount, o.total_tax, o.grand_total, o.amount_paid, o.balance_due, o.expected_delivery, o.delivered_at, o.notes, o.created_at, o.updated_at, c.first_name, c.last_name, c.phone as customer_phone
FROM orders o
JOIN customers c ON o.customer_id = c.id
WHERE o.shop_id = $1
  AND o.expected_delivery = $2::date
  AND o.status != 'delivered'
  AND o.status != 'cancelled'
ORDER BY o.id ASC
`

type ListOrdersDueParams struct {
	ShopID       int64       `json:"shop_id"`
	DeliveryDate pgtype.Date `json:"delivery_date"`
}

type ListOrdersDueRow struct {
	ID               int64              `json:"id"`
	ShopID           int64              `json:"shop_id"`
	CustomerID       int64              `json:"customer_id"`
	CreatedBy        pgtype.Int8        `json:"created_by"`
	OrderNumber      string             `json:"order_number"`
	OrderType        string             `json:"order_type"`
	Status           string             `json:"status"`
	PaymentStatus    string             `json:"payment_status"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	DiscountType     pgtype.Text        `json:"discount_type"`
	DiscountValue    pgtype.Numeric     `json:"discount_value"`
	DiscountAmount   pgtype.Numeric     `json:"discount_amount"`
	TaxableAmount    pgtype.Numeric     `json:"taxable_amount"`
	CgstAmount       pgtype.Numeric     `json:"cgst_amount"`
	SgstAmount       pgtype.Numeric     `json:"sgst_amount"`
	IgstAmount       pgtype.Numeric     `json:"igst_amount"`
	TotalTax         pgtype.Numeric     `json:"total_tax"`
	GrandTotal       pgtype.Numeric     `json:"grand_total"`
	AmountPaid       pgtype.Numeric     `json:"amount_paid"`
	BalanceDue       pgtype.Numeric     `json:"balance_due"`
	ExpectedDelivery pgtype.Date        `json:"expected_delivery"`
	DeliveredAt      pgtype.Timestamptz `json:"delivered_at"`
	Notes            pgtype.Text        `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	FirstName        string             `json:"first_name"`
	LastName         pgtype.Text        `json:"last_name"`
	CustomerPhone    pgtype.Text        `json:"customer_phone"`
}

func (q *Queries) ListOrdersDue(ctx context.Context, arg ListOrdersDueParams) ([]ListOrdersDueRow, error) {
	rows, err := q.db.Query(ctx, listOrdersDue, arg.ShopID, arg.DeliveryDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrdersDueRow{}
	for rows.Next() {
		var i ListOrdersDueRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.CustomerID,
			&i.CreatedBy,
			&i.OrderNumber,
			&i.OrderType,
			&i.Status,
			&i.PaymentStatus,
			&i.Subtotal,
			&i.DiscountType,
			&i.DiscountValue,
			&i.DiscountAmount,
			&i.TaxableAmount,
			&i.CgstAmount,
			&i.SgstAmount,
			&i.IgstAmount,
			&i.TotalTax,
			&i.GrandTotal,
			&i.AmountPaid,
			&i.BalanceDue,
			&i.ExpectedDelivery,
			&i.DeliveredAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET 
    subtotal = $3,
    discount_type = $4,
    discount_value = $5,
    discount_amount = $6,
    taxable_amount = $7,
    cgst_amount = $8,
    sgst_amount = $9,
    igst_amount = $10,
    total_tax = $11,
    grand_total = $12,
    balance_due = $12 - amount_paid,
    payment_status = CASE 
        WHEN amount_paid >= $12 THEN 'paid'
        WHEN amount_paid > 0 THEN 'partial'
        ELSE 'pending'
    END,
    expected_delivery = $13,
    notes = $14,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, customer_id, created_by, order_number, order_type, status, payment_status, subtotal, discount_type, discount_value, discount_amount, taxable_amount, cgst_amount, sgst_amount, igst_amount, total_tax, grand_total, amount_paid, balance_due, expected_delivery, delivered_at, notes, created_at, updated_at
`

type UpdateOrderParams struct {
	ID               int64          `json:"id"`
	ShopID           int64          `json:"shop_id"`
	Subtotal         pgtype.Numeric `json:"subtotal"`
	DiscountType     pgtype.Text    `json:"discount_type"`
	DiscountValue    pgtype.Numeric `json:"discount_value"`
	DiscountAmount   pgtype.Numeric `json:"discount_amount"`
	TaxableAmount    pgtype.Numeric `json:"taxable_amount"`
	CgstAmount       pgtype.Numeric `json:"cgst_amount"`
	SgstAmount       pgtype.Numeric `json:"sgst_amount"`
	IgstAmount       pgtype.Numeric `json:"igst_amount"`
	TotalTax         pgtype.Numeric `json:"total_tax"`
	GrandTotal       pgtype.Numeric `json:"grand_total"`
	ExpectedDelivery pgtype.Date    `json:"expected_delivery"`
	Notes            pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.ID,
		arg.ShopID,
		arg.Subtotal,
		arg.DiscountType,
		arg.DiscountValue,
		arg.DiscountAmount,
		arg.TaxableAmount,
		arg.CgstAmount,
		arg.SgstAmount,
		arg.IgstAmount,
		arg.TotalTax,
		arg.GrandTotal,
		arg.ExpectedDelivery,
		arg.Notes,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.CreatedBy,
		&i.OrderNumber,
		&i.OrderType,
		&i.Status,
		&i.PaymentStatus,
		&i.Subtotal,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.TaxableAmount,
		&i.CgstAmount,
		&i.SgstAmount,
		&i.IgstAmount,
		&i.TotalTax,
		&i.GrandTotal,
		&i.AmountPaid,
		&i.BalanceDue,
		&i.ExpectedDelivery,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderPaymentStatus = `-- name: UpdateOrderPaymentStatus :one
UPDATE orders
SET 
    amount_paid = amount_paid + $3::numeric,
    balance_due = grand_total - (amount_paid + $3::numeric),
    payment_status = CASE 
        WHEN (amount_paid + $3::numeric) >= grand_total THEN 'paid'
        WHEN (amount_paid + $3::numeric) > 0 THEN 'partial'
        ELSE 'pending'
    END,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, customer_id, created_by, order_number, order_type, status, payment_status, subtotal, discount_type, discount_value, discount_amount, taxable_amount, cgst_amount, sgst_amount, igst_amount, total_tax, grand_total, amount_paid, balance_due, expected_delivery, delivered_at, notes, created_at, updated_at
`

type UpdateOrderPaymentStatusParams struct {
	ID         int64          `json:"id"`
	ShopID     int64          `json:"shop_id"`
	AmountPaid pgtype.Numeric `json:"amount_paid"`
}

func (q *Queries) UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderPaymentStatus, arg.ID, arg.ShopID, arg.AmountPaid)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.CreatedBy,
		&i.OrderNumber,
		&i.OrderType,
		&i.Status,
		&i.PaymentStatus,
		&i.Subtotal,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.TaxableAmount,
		&i.CgstAmount,
		&i.SgstAmount,
		&i.IgstAmount,
		&i.TotalTax,
		&i.GrandTotal,
		&i.AmountPaid,
		&i.BalanceDue,
		&i.ExpectedDelivery,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET 
    status = $3::text,
    delivered_at = CASE WHEN $3::text = 'delivered' THEN now() ELSE delivered_at END,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, customer_id, created_by, order_number, order_type, status, payment_status, subtotal, discount_type, discount_value, discount_amount, taxable_amount, cgst_amount, sgst_amount, igst_amount, total_tax, grand_total, amount_paid, balance_due, expected_delivery, delivered_at, notes, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     int64  `json:"id"`
	ShopID int64  `json:"shop_id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.ShopID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.CustomerID,
		&i.CreatedBy,
		&i.OrderNumber,
		&i.OrderType,
		&i.Status,
		&i.PaymentStatus,
		&i.Subtotal,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountAmount,
		&i.TaxableAmount,
		&i.CgstAmount,
		&i.SgstAmount,
		&i.IgstAmount,
		&i.TotalTax,
		&i.GrandTotal,
		&i.AmountPaid,
		&i.BalanceDue,
		&i.ExpectedDelivery,
		&i.DeliveredAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
