// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProducts = `-- name: CountProducts :one
SELECT COUNT(*) FROM products
WHERE shop_id = $1
  AND is_active = true
  AND (
    $2::text = '' OR
    name ILIKE '%' || $2 || '%' OR
    sku ILIKE '%' || $2 || '%' OR
    brand ILIKE '%' || $2 || '%' OR
    model ILIKE '%' || $2 || '%' OR
    barcode ILIKE '%' || $2 || '%'
  )
  AND ($3::text = 'all' OR category = $3)
  AND (
    $4::text = 'any' OR
    ($4::text = 'in_stock' AND current_stock > 0) OR
    ($4::text = 'out_of_stock' AND current_stock <= 0) OR
    ($4::text = 'low_stock' AND current_stock <= min_stock_level)
  )
`

type CountProductsParams struct {
	ShopID  int64  `json:"shop_id"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts,
		arg.ShopID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    shop_id, name, sku, category, brand, model, color, size, description,
    purchase_price, selling_price, hsn_code, gst_rate, current_stock, min_stock_level,
    barcode, image_url, frame_type, frame_material, frame_shape, temple_length,
    bridge_width, lens_width, gender_target, cl_replacement_schedule, cl_base_curve,
    cl_diameter, cl_water_content, cl_material
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21,
    $22, $23, $24, $25, $26,
    $27, $28, $29
)
RETURNING id, shop_id, name, sku, category, brand, model, color, size, description, purchase_price, selling_price, hsn_code, gst_rate, current_stock, min_stock_level, barcode, image_url, is_active, frame_type, frame_material, frame_shape, temple_length, bridge_width, lens_width, gender_target, cl_replacement_schedule, cl_base_curve, cl_diameter, cl_water_content, cl_material, created_at, updated_at
`

type CreateProductParams struct {
	ShopID                int64          `json:"shop_id"`
	Name                  string         `json:"name"`
	Sku                   pgtype.Text    `json:"sku"`
	Category              string         `json:"category"`
	Brand                 pgtype.Text    `json:"brand"`
	Model                 pgtype.Text    `json:"model"`
	Color                 pgtype.Text    `json:"color"`
	Size                  pgtype.Text    `json:"size"`
	Description           pgtype.Text    `json:"description"`
	PurchasePrice         pgtype.Numeric `json:"purchase_price"`
	SellingPrice          pgtype.Numeric `json:"selling_price"`
	HsnCode               pgtype.Text    `json:"hsn_code"`
	GstRate               pgtype.Numeric `json:"gst_rate"`
	CurrentStock          int32          `json:"current_stock"`
	MinStockLevel         int32          `json:"min_stock_level"`
	Barcode               pgtype.Text    `json:"barcode"`
	ImageUrl              pgtype.Text    `json:"image_url"`
	FrameType             pgtype.Text    `json:"frame_type"`
	FrameMaterial         pgtype.Text    `json:"frame_material"`
	FrameShape            pgtype.Text    `json:"frame_shape"`
	TempleLength          pgtype.Numeric `json:"temple_length"`
	BridgeWidth           pgtype.Numeric `json:"bridge_width"`
	LensWidth             pgtype.Numeric `json:"lens_width"`
	GenderTarget          pgtype.Text    `json:"gender_target"`
	ClReplacementSchedule pgtype.Text    `json:"cl_replacement_schedule"`
	ClBaseCurve           pgtype.Numeric `json:"cl_base_curve"`
	ClDiameter            pgtype.Numeric `json:"cl_diameter"`
	ClWaterContent        pgtype.Text    `json:"cl_water_content"`
	ClMaterial            pgtype.Text    `json:"cl_material"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ShopID,
		arg.Name,
		arg.Sku,
		arg.Category,
		arg.Brand,
		arg.Model,
		arg.Color,
		arg.Size,
		arg.Description,
		arg.PurchasePrice,
		arg.SellingPrice,
		arg.HsnCode,
		arg.GstRate,
		arg.CurrentStock,
		arg.MinStockLevel,
		arg.Barcode,
		arg.ImageUrl,
		arg.FrameType,
		arg.FrameMaterial,
		arg.FrameShape,
		arg.TempleLength,
		arg.BridgeWidth,
		arg.LensWidth,
		arg.GenderTarget,
		arg.ClReplacementSchedule,
		arg.ClBaseCurve,
		arg.ClDiameter,
		arg.ClWaterContent,
		arg.ClMaterial,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Sku,
		&i.Category,
		&i.Brand,
		&i.Model,
		&i.Color,
		&i.Size,
		&i.Description,
		&i.PurchasePrice,
		&i.SellingPrice,
		&i.HsnCode,
		&i.GstRate,
		&i.CurrentStock,
		&i.MinStockLevel,
		&i.Barcode,
		&i.ImageUrl,
		&i.IsActive,
		&i.FrameType,
		&i.FrameMaterial,
		&i.FrameShape,
		&i.TempleLength,
		&i.BridgeWidth,
		&i.LensWidth,
		&i.GenderTarget,
		&i.ClReplacementSchedule,
		&i.ClBaseCurve,
		&i.ClDiameter,
		&i.ClWaterContent,
		&i.ClMaterial,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLowStockProducts = `-- name: GetLowStockProducts :many
SELECT id, shop_id, name, sku, category, brand, model, color, size, description, purchase_price, selling_price, hsn_code, gst_rate, current_stock, min_stock_level, barcode, image_url, is_active, frame_type, frame_material, frame_shape, temple_length, bridge_width, lens_width, gender_target, cl_replacement_schedule, cl_base_curve, cl_diameter, cl_water_content, cl_material, created_at, updated_at FROM products
WHERE shop_id = $1
  AND is_active = true
  AND current_stock <= min_stock_level
ORDER BY current_stock ASC
`

func (q *Queries) GetLowStockProducts(ctx context.Context, shopID int64) ([]Product, error) {
	rows, err := q.db.Query(ctx, getLowStockProducts, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Sku,
			&i.Category,
			&i.Brand,
			&i.Model,
			&i.Color,
			&i.Size,
			&i.Description,
			&i.PurchasePrice,
			&i.SellingPrice,
			&i.HsnCode,
			&i.GstRate,
			&i.CurrentStock,
			&i.MinStockLevel,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.FrameType,
			&i.FrameMaterial,
			&i.FrameShape,
			&i.TempleLength,
			&i.BridgeWidth,
			&i.LensWidth,
			&i.GenderTarget,
			&i.ClReplacementSchedule,
			&i.ClBaseCurve,
			&i.ClDiameter,
			&i.ClWaterContent,
			&i.ClMaterial,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, shop_id, name, sku, category, brand, model, color, size, description, purchase_price, selling_price, hsn_code, gst_rate, current_stock, min_stock_level, barcode, image_url, is_active, frame_type, frame_material, frame_shape, temple_length, bridge_width, lens_width, gender_target, cl_replacement_schedule, cl_base_curve, cl_diameter, cl_water_content, cl_material, created_at, updated_at FROM products
WHERE id = $1 AND shop_id = $2 LIMIT 1
`

type GetProductByIDParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

func (q *Queries) GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, arg.ID, arg.ShopID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Sku,
		&i.Category,
		&i.Brand,
		&i.Model,
		&i.Color,
		&i.Size,
		&i.Description,
		&i.PurchasePrice,
		&i.SellingPrice,
		&i.HsnCode,
		&i.GstRate,
		&i.CurrentStock,
		&i.MinStockLevel,
		&i.Barcode,
		&i.ImageUrl,
		&i.IsActive,
		&i.FrameType,
		&i.FrameMaterial,
		&i.FrameShape,
		&i.TempleLength,
		&i.BridgeWidth,
		&i.LensWidth,
		&i.GenderTarget,
		&i.ClReplacementSchedule,
		&i.ClBaseCurve,
		&i.ClDiameter,
		&i.ClWaterContent,
		&i.ClMaterial,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, shop_id, name, sku, category, brand, model, color, size, description, purchase_price, selling_price, hsn_code, gst_rate, current_stock, min_stock_level, barcode, image_url, is_active, frame_type, frame_material, frame_shape, temple_length, bridge_width, lens_width, gender_target, cl_replacement_schedule, cl_base_curve, cl_diameter, cl_water_content, cl_material, created_at, updated_at FROM products
WHERE shop_id = $1
  AND is_active = true
  AND (
    $2::text = '' OR
    name ILIKE '%' || $2 || '%' OR
    sku ILIKE '%' || $2 || '%' OR
    brand ILIKE '%' || $2 || '%' OR
    model ILIKE '%' || $2 || '%' OR
    barcode ILIKE '%' || $2 || '%'
  )
  AND ($3::text = 'all' OR category = $3)
  AND (
    $4::text = 'any' OR
    ($4::text = 'in_stock' AND current_stock > 0) OR
    ($4::text = 'out_of_stock' AND current_stock <= 0) OR
    ($4::text = 'low_stock' AND current_stock <= min_stock_level)
  )
ORDER BY 
  CASE WHEN $5::text = 'name_asc' THEN name END ASC,
  CASE WHEN $5::text = 'price_asc' THEN selling_price END ASC,
  CASE WHEN $5::text = 'price_desc' THEN selling_price END DESC,
  CASE WHEN $5::text = 'stock_asc' THEN current_stock END ASC,
  CASE WHEN $5::text = 'type_name' OR $5::text = '' THEN category END ASC, name ASC
LIMIT $6 OFFSET $7
`

type ListProductsParams struct {
	ShopID  int64  `json:"shop_id"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 string `json:"column_4"`
	Column5 string `json:"column_5"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.ShopID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.Sku,
			&i.Category,
			&i.Brand,
			&i.Model,
			&i.Color,
			&i.Size,
			&i.Description,
			&i.PurchasePrice,
			&i.SellingPrice,
			&i.HsnCode,
			&i.GstRate,
			&i.CurrentStock,
			&i.MinStockLevel,
			&i.Barcode,
			&i.ImageUrl,
			&i.IsActive,
			&i.FrameType,
			&i.FrameMaterial,
			&i.FrameShape,
			&i.TempleLength,
			&i.BridgeWidth,
			&i.LensWidth,
			&i.GenderTarget,
			&i.ClReplacementSchedule,
			&i.ClBaseCurve,
			&i.ClDiameter,
			&i.ClWaterContent,
			&i.ClMaterial,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProduct = `-- name: SoftDeleteProduct :exec
UPDATE products
SET is_active = false, updated_at = now()
WHERE id = $1 AND shop_id = $2
`

type SoftDeleteProductParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

func (q *Queries) SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) error {
	_, err := q.db.Exec(ctx, softDeleteProduct, arg.ID, arg.ShopID)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    name = $3,
    sku = $4,
    category = $5,
    brand = $6,
    model = $7,
    color = $8,
    size = $9,
    description = $10,
    purchase_price = $11,
    selling_price = $12,
    hsn_code = $13,
    gst_rate = $14,
    min_stock_level = $15,
    barcode = $16,
    image_url = $17,
    frame_type = $18,
    frame_material = $19,
    frame_shape = $20,
    temple_length = $21,
    bridge_width = $22,
    lens_width = $23,
    gender_target = $24,
    cl_replacement_schedule = $25,
    cl_base_curve = $26,
    cl_diameter = $27,
    cl_water_content = $28,
    cl_material = $29,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, name, sku, category, brand, model, color, size, description, purchase_price, selling_price, hsn_code, gst_rate, current_stock, min_stock_level, barcode, image_url, is_active, frame_type, frame_material, frame_shape, temple_length, bridge_width, lens_width, gender_target, cl_replacement_schedule, cl_base_curve, cl_diameter, cl_water_content, cl_material, created_at, updated_at
`

type UpdateProductParams struct {
	ID                    int64          `json:"id"`
	ShopID                int64          `json:"shop_id"`
	Name                  string         `json:"name"`
	Sku                   pgtype.Text    `json:"sku"`
	Category              string         `json:"category"`
	Brand                 pgtype.Text    `json:"brand"`
	Model                 pgtype.Text    `json:"model"`
	Color                 pgtype.Text    `json:"color"`
	Size                  pgtype.Text    `json:"size"`
	Description           pgtype.Text    `json:"description"`
	PurchasePrice         pgtype.Numeric `json:"purchase_price"`
	SellingPrice          pgtype.Numeric `json:"selling_price"`
	HsnCode               pgtype.Text    `json:"hsn_code"`
	GstRate               pgtype.Numeric `json:"gst_rate"`
	MinStockLevel         int32          `json:"min_stock_level"`
	Barcode               pgtype.Text    `json:"barcode"`
	ImageUrl              pgtype.Text    `json:"image_url"`
	FrameType             pgtype.Text    `json:"frame_type"`
	FrameMaterial         pgtype.Text    `json:"frame_material"`
	FrameShape            pgtype.Text    `json:"frame_shape"`
	TempleLength          pgtype.Numeric `json:"temple_length"`
	BridgeWidth           pgtype.Numeric `json:"bridge_width"`
	LensWidth             pgtype.Numeric `json:"lens_width"`
	GenderTarget          pgtype.Text    `json:"gender_target"`
	ClReplacementSchedule pgtype.Text    `json:"cl_replacement_schedule"`
	ClBaseCurve           pgtype.Numeric `json:"cl_base_curve"`
	ClDiameter            pgtype.Numeric `json:"cl_diameter"`
	ClWaterContent        pgtype.Text    `json:"cl_water_content"`
	ClMaterial            pgtype.Text    `json:"cl_material"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.ShopID,
		arg.Name,
		arg.Sku,
		arg.Category,
		arg.Brand,
		arg.Model,
		arg.Color,
		arg.Size,
		arg.Description,
		arg.PurchasePrice,
		arg.SellingPrice,
		arg.HsnCode,
		arg.GstRate,
		arg.MinStockLevel,
		arg.Barcode,
		arg.ImageUrl,
		arg.FrameType,
		arg.FrameMaterial,
		arg.FrameShape,
		arg.TempleLength,
		arg.BridgeWidth,
		arg.LensWidth,
		arg.GenderTarget,
		arg.ClReplacementSchedule,
		arg.ClBaseCurve,
		arg.ClDiameter,
		arg.ClWaterContent,
		arg.ClMaterial,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Sku,
		&i.Category,
		&i.Brand,
		&i.Model,
		&i.Color,
		&i.Size,
		&i.Description,
		&i.PurchasePrice,
		&i.SellingPrice,
		&i.HsnCode,
		&i.GstRate,
		&i.CurrentStock,
		&i.MinStockLevel,
		&i.Barcode,
		&i.ImageUrl,
		&i.IsActive,
		&i.FrameType,
		&i.FrameMaterial,
		&i.FrameShape,
		&i.TempleLength,
		&i.BridgeWidth,
		&i.LensWidth,
		&i.GenderTarget,
		&i.ClReplacementSchedule,
		&i.ClBaseCurve,
		&i.ClDiameter,
		&i.ClWaterContent,
		&i.ClMaterial,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET 
    current_stock = current_stock + $3,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, name, sku, category, brand, model, color, size, description, purchase_price, selling_price, hsn_code, gst_rate, current_stock, min_stock_level, barcode, image_url, is_active, frame_type, frame_material, frame_shape, temple_length, bridge_width, lens_width, gender_target, cl_replacement_schedule, cl_base_curve, cl_diameter, cl_water_content, cl_material, created_at, updated_at
`

type UpdateProductStockParams struct {
	ID           int64 `json:"id"`
	ShopID       int64 `json:"shop_id"`
	CurrentStock int32 `json:"current_stock"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.ID, arg.ShopID, arg.CurrentStock)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.Sku,
		&i.Category,
		&i.Brand,
		&i.Model,
		&i.Color,
		&i.Size,
		&i.Description,
		&i.PurchasePrice,
		&i.SellingPrice,
		&i.HsnCode,
		&i.GstRate,
		&i.CurrentStock,
		&i.MinStockLevel,
		&i.Barcode,
		&i.ImageUrl,
		&i.IsActive,
		&i.FrameType,
		&i.FrameMaterial,
		&i.FrameShape,
		&i.TempleLength,
		&i.BridgeWidth,
		&i.LensWidth,
		&i.GenderTarget,
		&i.ClReplacementSchedule,
		&i.ClBaseCurve,
		&i.ClDiameter,
		&i.ClWaterContent,
		&i.ClMaterial,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
