// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_images.sql

package pgdb

import (
	"context"
)

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (
    product_id, image_url, sort_order
) VALUES (
    $1, $2, $3
)
RETURNING id, product_id, image_url, sort_order, created_at
`

type CreateProductImageParams struct {
	ProductID int64  `json:"product_id"`
	ImageUrl  string `json:"image_url"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage, arg.ProductID, arg.ImageUrl, arg.SortOrder)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ImageUrl,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProductImage = `-- name: DeleteProductImage :exec
DELETE FROM product_images
WHERE id = $1
`

func (q *Queries) DeleteProductImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProductImage, id)
	return err
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, image_url, sort_order, created_at FROM product_images
WHERE product_id = $1
ORDER BY sort_order ASC, id ASC
`

func (q *Queries) ListProductImages(ctx context.Context, productID int64) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductImage{}
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ImageUrl,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
