// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchase_bills.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPurchaseBills = `-- name: CountPurchaseBills :one
SELECT COUNT(*)
FROM purchase_bills pb
JOIN vendors v ON pb.vendor_id = v.id
WHERE pb.shop_id = $1
  AND (
    $2::text = '' OR
    pb.bill_number ILIKE '%' || $2 || '%' OR
    v.name ILIKE '%' || $2 || '%'
  )
  AND ($3::text = 'all' OR pb.status = $3)
  AND ($4::bigint = 0 OR pb.vendor_id = $4)
  AND ($5::date IS NULL OR pb.bill_date >= $5)
  AND ($6::date IS NULL OR pb.bill_date <= $6)
`

type CountPurchaseBillsParams struct {
	ShopID   int64       `json:"shop_id"`
	Search   string      `json:"search"`
	Status   string      `json:"status"`
	VendorID int64       `json:"vendor_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) CountPurchaseBills(ctx context.Context, arg CountPurchaseBillsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseBills,
		arg.ShopID,
		arg.Search,
		arg.Status,
		arg.VendorID,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPurchaseBill = `-- name: CreatePurchaseBill :one
INSERT INTO purchase_bills (
    shop_id, vendor_id, bill_number, bill_date, due_date,
    subtotal, tax_amount, total_amount, amount_paid, balance, status, notes, created_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, shop_id, vendor_id, bill_number, bill_date, due_date, subtotal, tax_amount, total_amount, amount_paid, balance, status, notes, created_by, created_at, updated_at
`

type CreatePurchaseBillParams struct {
	ShopID      int64          `json:"shop_id"`
	VendorID    int64          `json:"vendor_id"`
	BillNumber  string         `json:"bill_number"`
	BillDate    pgtype.Date    `json:"bill_date"`
	DueDate     pgtype.Date    `json:"due_date"`
	Subtotal    pgtype.Numeric `json:"subtotal"`
	TaxAmount   pgtype.Numeric `json:"tax_amount"`
	TotalAmount pgtype.Numeric `json:"total_amount"`
	AmountPaid  pgtype.Numeric `json:"amount_paid"`
	Balance     pgtype.Numeric `json:"balance"`
	Status      string         `json:"status"`
	Notes       pgtype.Text    `json:"notes"`
	CreatedBy   pgtype.Int8    `json:"created_by"`
}

func (q *Queries) CreatePurchaseBill(ctx context.Context, arg CreatePurchaseBillParams) (PurchaseBill, error) {
	row := q.db.QueryRow(ctx, createPurchaseBill,
		arg.ShopID,
		arg.VendorID,
		arg.BillNumber,
		arg.BillDate,
		arg.DueDate,
		arg.Subtotal,
		arg.TaxAmount,
		arg.TotalAmount,
		arg.AmountPaid,
		arg.Balance,
		arg.Status,
		arg.Notes,
		arg.CreatedBy,
	)
	var i PurchaseBill
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.VendorID,
		&i.BillNumber,
		&i.BillDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.Balance,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPurchaseBillByID = `-- name: GetPurchaseBillByID :one
SELECT pb.id, pb.shop_id, pb.vendor_id, pb.bill_number, pb.bill_date, pb.due_date, pb.subtotal, pb.tax_amount, pb.total_amount, pb.amount_paid, pb.balance, pb.status, pb.notes, pb.created_by, pb.created_at, pb.updated_at, v.name as vendor_name, u.full_name as created_by_name
FROM purchase_bills pb
JOIN vendors v ON pb.vendor_id = v.id
LEFT JOIN users u ON pb.created_by = u.id
WHERE pb.id = $1 AND pb.shop_id = $2 LIMIT 1
`

type GetPurchaseBillByIDParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

type GetPurchaseBillByIDRow struct {
	ID            int64              `json:"id"`
	ShopID        int64              `json:"shop_id"`
	VendorID      int64              `json:"vendor_id"`
	BillNumber    string             `json:"bill_number"`
	BillDate      pgtype.Date        `json:"bill_date"`
	DueDate       pgtype.Date        `json:"due_date"`
	Subtotal      pgtype.Numeric     `json:"subtotal"`
	TaxAmount     pgtype.Numeric     `json:"tax_amount"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	AmountPaid    pgtype.Numeric     `json:"amount_paid"`
	Balance       pgtype.Numeric     `json:"balance"`
	Status        string             `json:"status"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	VendorName    string             `json:"vendor_name"`
	CreatedByName pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) GetPurchaseBillByID(ctx context.Context, arg GetPurchaseBillByIDParams) (GetPurchaseBillByIDRow, error) {
	row := q.db.QueryRow(ctx, getPurchaseBillByID, arg.ID, arg.ShopID)
	var i GetPurchaseBillByIDRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.VendorID,
		&i.BillNumber,
		&i.BillDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.Balance,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VendorName,
		&i.CreatedByName,
	)
	return i, err
}

const listPurchaseBills = `-- name: ListPurchaseBills :many
SELECT pb.id, pb.shop_id, pb.vendor_id, pb.bill_number, pb.bill_date, pb.due_date, pb.subtotal, pb.tax_amount, pb.total_amount, pb.amount_paid, pb.balance, pb.status, pb.notes, pb.created_by, pb.created_at, pb.updated_at, v.name as vendor_name, u.full_name as created_by_name
FROM purchase_bills pb
JOIN vendors v ON pb.vendor_id = v.id
LEFT JOIN users u ON pb.created_by = u.id
WHERE pb.shop_id = $1
  AND (
    $2::text = '' OR
    pb.bill_number ILIKE '%' || $2 || '%' OR
    v.name ILIKE '%' || $2 || '%'
  )
  AND ($3::text = 'all' OR pb.status = $3)
  AND ($4::bigint = 0 OR pb.vendor_id = $4)
  AND ($5::date IS NULL OR pb.bill_date >= $5)
  AND ($6::date IS NULL OR pb.bill_date <= $6)
ORDER BY pb.bill_date DESC, pb.id DESC
LIMIT $8 OFFSET $7
`

type ListPurchaseBillsParams struct {
	ShopID      int64       `json:"shop_id"`
	Search      string      `json:"search"`
	Status      string      `json:"status"`
	VendorID    int64       `json:"vendor_id"`
	FromDate    pgtype.Date `json:"from_date"`
	ToDate      pgtype.Date `json:"to_date"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListPurchaseBillsRow struct {
	ID            int64              `json:"id"`
	ShopID        int64              `json:"shop_id"`
	VendorID      int64              `json:"vendor_id"`
	BillNumber    string             `json:"bill_number"`
	BillDate      pgtype.Date        `json:"bill_date"`
	DueDate       pgtype.Date        `json:"due_date"`
	Subtotal      pgtype.Numeric     `json:"subtotal"`
	TaxAmount     pgtype.Numeric     `json:"tax_amount"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	AmountPaid    pgtype.Numeric     `json:"amount_paid"`
	Balance       pgtype.Numeric     `json:"balance"`
	Status        string             `json:"status"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	VendorName    string             `json:"vendor_name"`
	CreatedByName pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListPurchaseBills(ctx context.Context, arg ListPurchaseBillsParams) ([]ListPurchaseBillsRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseBills,
		arg.ShopID,
		arg.Search,
		arg.Status,
		arg.VendorID,
		arg.FromDate,
		arg.ToDate,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseBillsRow{}
	for rows.Next() {
		var i ListPurchaseBillsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.VendorID,
			&i.BillNumber,
			&i.BillDate,
			&i.DueDate,
			&i.Subtotal,
			&i.TaxAmount,
			&i.TotalAmount,
			&i.AmountPaid,
			&i.Balance,
			&i.Status,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VendorName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePurchaseBillPayment = `-- name: UpdatePurchaseBillPayment :one
UPDATE purchase_bills
SET 
    amount_paid = amount_paid + $3,
    balance = total_amount - (amount_paid + $3),
    status = CASE 
        WHEN (amount_paid + $3) >= total_amount THEN 'paid'
        WHEN (amount_paid + $3) > 0 THEN 'partial'
        ELSE 'pending'
    END,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, vendor_id, bill_number, bill_date, due_date, subtotal, tax_amount, total_amount, amount_paid, balance, status, notes, created_by, created_at, updated_at
`

type UpdatePurchaseBillPaymentParams struct {
	ID         int64          `json:"id"`
	ShopID     int64          `json:"shop_id"`
	AmountPaid pgtype.Numeric `json:"amount_paid"`
}

func (q *Queries) UpdatePurchaseBillPayment(ctx context.Context, arg UpdatePurchaseBillPaymentParams) (PurchaseBill, error) {
	row := q.db.QueryRow(ctx, updatePurchaseBillPayment, arg.ID, arg.ShopID, arg.AmountPaid)
	var i PurchaseBill
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.VendorID,
		&i.BillNumber,
		&i.BillDate,
		&i.DueDate,
		&i.Subtotal,
		&i.TaxAmount,
		&i.TotalAmount,
		&i.AmountPaid,
		&i.Balance,
		&i.Status,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
