// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchase_bill_items.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurchaseBillItem = `-- name: CreatePurchaseBillItem :one
INSERT INTO purchase_bill_items (
    purchase_bill_id, product_id, name, quantity, unit_price, tax_rate, tax_amount, total_price
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, purchase_bill_id, product_id, name, quantity, unit_price, tax_rate, tax_amount, total_price, created_at
`

type CreatePurchaseBillItemParams struct {
	PurchaseBillID int64          `json:"purchase_bill_id"`
	ProductID      pgtype.Int8    `json:"product_id"`
	Name           string         `json:"name"`
	Quantity       int32          `json:"quantity"`
	UnitPrice      pgtype.Numeric `json:"unit_price"`
	TaxRate        pgtype.Numeric `json:"tax_rate"`
	TaxAmount      pgtype.Numeric `json:"tax_amount"`
	TotalPrice     pgtype.Numeric `json:"total_price"`
}

func (q *Queries) CreatePurchaseBillItem(ctx context.Context, arg CreatePurchaseBillItemParams) (PurchaseBillItem, error) {
	row := q.db.QueryRow(ctx, createPurchaseBillItem,
		arg.PurchaseBillID,
		arg.ProductID,
		arg.Name,
		arg.Quantity,
		arg.UnitPrice,
		arg.TaxRate,
		arg.TaxAmount,
		arg.TotalPrice,
	)
	var i PurchaseBillItem
	err := row.Scan(
		&i.ID,
		&i.PurchaseBillID,
		&i.ProductID,
		&i.Name,
		&i.Quantity,
		&i.UnitPrice,
		&i.TaxRate,
		&i.TaxAmount,
		&i.TotalPrice,
		&i.CreatedAt,
	)
	return i, err
}

const listPurchaseBillItems = `-- name: ListPurchaseBillItems :many
SELECT id, purchase_bill_id, product_id, name, quantity, unit_price, tax_rate, tax_amount, total_price, created_at FROM purchase_bill_items
WHERE purchase_bill_id = $1
ORDER BY id ASC
`

func (q *Queries) ListPurchaseBillItems(ctx context.Context, purchaseBillID int64) ([]PurchaseBillItem, error) {
	rows, err := q.db.Query(ctx, listPurchaseBillItems, purchaseBillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurchaseBillItem{}
	for rows.Next() {
		var i PurchaseBillItem
		if err := rows.Scan(
			&i.ID,
			&i.PurchaseBillID,
			&i.ProductID,
			&i.Name,
			&i.Quantity,
			&i.UnitPrice,
			&i.TaxRate,
			&i.TaxAmount,
			&i.TotalPrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
