// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelOrder(ctx context.Context, arg CancelOrderParams) (Order, error)
	CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error)
	CountExpenses(ctx context.Context, arg CountExpensesParams) (int64, error)
	CountEyeTests(ctx context.Context, arg CountEyeTestsParams) (int64, error)
	CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountPurchaseBills(ctx context.Context, arg CountPurchaseBillsParams) (int64, error)
	CountRepairs(ctx context.Context, arg CountRepairsParams) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateCustomerNote(ctx context.Context, arg CreateCustomerNoteParams) (CustomerNote, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error)
	CreateEyeTest(ctx context.Context, arg CreateEyeTestParams) (EyeTest, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOrderPayment(ctx context.Context, arg CreateOrderPaymentParams) (OrderPayment, error)
	CreateOrderPrescription(ctx context.Context, arg CreateOrderPrescriptionParams) (OrderPrescription, error)
	CreateOrderStatusHistory(ctx context.Context, arg CreateOrderStatusHistoryParams) (OrderStatusHistory, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error)
	CreatePurchaseBill(ctx context.Context, arg CreatePurchaseBillParams) (PurchaseBill, error)
	CreatePurchaseBillItem(ctx context.Context, arg CreatePurchaseBillItemParams) (PurchaseBillItem, error)
	CreateRepair(ctx context.Context, arg CreateRepairParams) (Repair, error)
	CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error)
	CreateVendorPayment(ctx context.Context, arg CreateVendorPaymentParams) (VendorPayment, error)
	DeleteCustomerNote(ctx context.Context, id int64) error
	DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error
	DeleteExpenseCategory(ctx context.Context, arg DeleteExpenseCategoryParams) error
	DeleteEyeTest(ctx context.Context, arg DeleteEyeTestParams) error
	DeleteOrderItems(ctx context.Context, orderID int64) error
	DeleteOrderPrescription(ctx context.Context, orderID int64) error
	DeleteProductImage(ctx context.Context, id int64) error
	DeleteRepair(ctx context.Context, arg DeleteRepairParams) error
	DeleteUser(ctx context.Context, id int64) error
	GetAllTranslationsForLanguage(ctx context.Context, arg GetAllTranslationsForLanguageParams) ([]GetAllTranslationsForLanguageRow, error)
	GetBatchTranslations(ctx context.Context, arg GetBatchTranslationsParams) ([]GetBatchTranslationsRow, error)
	GetCustomerByID(ctx context.Context, arg GetCustomerByIDParams) (Customer, error)
	GetCustomerCities(ctx context.Context, shopID int64) ([]pgtype.Text, error)
	GetCustomerStats(ctx context.Context, shopID int64) (GetCustomerStatsRow, error)
	GetDailySalesForRange(ctx context.Context, arg GetDailySalesForRangeParams) ([]GetDailySalesForRangeRow, error)
	GetDashboardOverviewStats(ctx context.Context, shopID int64) (GetDashboardOverviewStatsRow, error)
	GetExpenseByID(ctx context.Context, arg GetExpenseByIDParams) (GetExpenseByIDRow, error)
	GetExpensesSummary(ctx context.Context, arg GetExpensesSummaryParams) (GetExpensesSummaryRow, error)
	GetEyeTestByID(ctx context.Context, arg GetEyeTestByIDParams) (GetEyeTestByIDRow, error)
	GetGSTSummaryReport(ctx context.Context, arg GetGSTSummaryReportParams) (GetGSTSummaryReportRow, error)
	GetLowStockProducts(ctx context.Context, shopID int64) ([]Product, error)
	GetOrderByID(ctx context.Context, arg GetOrderByIDParams) (GetOrderByIDRow, error)
	GetOrderByNumber(ctx context.Context, arg GetOrderByNumberParams) (GetOrderByNumberRow, error)
	GetOrderPrescription(ctx context.Context, orderID int64) (OrderPrescription, error)
	GetPaymentModeBreakdown(ctx context.Context, arg GetPaymentModeBreakdownParams) ([]GetPaymentModeBreakdownRow, error)
	GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error)
	GetPurchaseBillByID(ctx context.Context, arg GetPurchaseBillByIDParams) (GetPurchaseBillByIDRow, error)
	GetRepairByID(ctx context.Context, arg GetRepairByIDParams) (GetRepairByIDRow, error)
	GetRepairByNumber(ctx context.Context, arg GetRepairByNumberParams) (GetRepairByNumberRow, error)
	GetRepairStats(ctx context.Context, shopID int64) (GetRepairStatsRow, error)
	GetShopByID(ctx context.Context, id int64) (Shop, error)
	GetShopSetting(ctx context.Context, arg GetShopSettingParams) (ShopSetting, error)
	GetStockValuationSummary(ctx context.Context, shopID int64) (GetStockValuationSummaryRow, error)
	GetTopSellingProducts(ctx context.Context, arg GetTopSellingProductsParams) ([]GetTopSellingProductsRow, error)
	GetTotalPaidForOrder(ctx context.Context, orderID int64) (pgtype.Numeric, error)
	GetTranslation(ctx context.Context, arg GetTranslationParams) (TranslationCache, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetVendorByID(ctx context.Context, arg GetVendorByIDParams) (Vendor, error)
	IncrementAndGetNextInvoiceNumber(ctx context.Context, id int64) (IncrementAndGetNextInvoiceNumberRow, error)
	IncrementAndGetNextOrderNumber(ctx context.Context, id int64) (IncrementAndGetNextOrderNumberRow, error)
	ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ListActivityLogsRow, error)
	ListCustomerNotes(ctx context.Context, customerID int64) ([]ListCustomerNotesRow, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListExpenseCategories(ctx context.Context, shopID int64) ([]ExpenseCategory, error)
	ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error)
	ListEyeTests(ctx context.Context, arg ListEyeTestsParams) ([]ListEyeTestsRow, error)
	ListEyeTestsByCustomer(ctx context.Context, arg ListEyeTestsByCustomerParams) ([]ListEyeTestsByCustomerRow, error)
	ListOrderItems(ctx context.Context, orderID int64) ([]OrderItem, error)
	ListOrderPayments(ctx context.Context, orderID int64) ([]ListOrderPaymentsRow, error)
	ListOrderStatusHistory(ctx context.Context, orderID int64) ([]ListOrderStatusHistoryRow, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error)
	ListOrdersByCustomer(ctx context.Context, arg ListOrdersByCustomerParams) ([]ListOrdersByCustomerRow, error)
	ListOrdersDue(ctx context.Context, arg ListOrdersDueParams) ([]ListOrdersDueRow, error)
	ListProductImages(ctx context.Context, productID int64) ([]ProductImage, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListPurchaseBillItems(ctx context.Context, purchaseBillID int64) ([]PurchaseBillItem, error)
	ListPurchaseBills(ctx context.Context, arg ListPurchaseBillsParams) ([]ListPurchaseBillsRow, error)
	ListRepairs(ctx context.Context, arg ListRepairsParams) ([]ListRepairsRow, error)
	ListShopSettings(ctx context.Context, shopID int64) ([]ShopSetting, error)
	ListStockMovements(ctx context.Context, arg ListStockMovementsParams) ([]ListStockMovementsRow, error)
	ListStockMovementsByProduct(ctx context.Context, arg ListStockMovementsByProductParams) ([]ListStockMovementsByProductRow, error)
	ListUsersByShop(ctx context.Context, shopID int64) ([]User, error)
	ListVendorPayments(ctx context.Context, arg ListVendorPaymentsParams) ([]ListVendorPaymentsRow, error)
	ListVendorPaymentsByVendor(ctx context.Context, arg ListVendorPaymentsByVendorParams) ([]ListVendorPaymentsByVendorRow, error)
	ListVendors(ctx context.Context, shopID int64) ([]Vendor, error)
	SetCustomerOutstandingDues(ctx context.Context, arg SetCustomerOutstandingDuesParams) error
	SoftDeleteCustomer(ctx context.Context, arg SoftDeleteCustomerParams) error
	SoftDeleteProduct(ctx context.Context, arg SoftDeleteProductParams) error
	SoftDeleteVendor(ctx context.Context, arg SoftDeleteVendorParams) error
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateCustomerFinancials(ctx context.Context, arg UpdateCustomerFinancialsParams) error
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
	UpdateEyeTest(ctx context.Context, arg UpdateEyeTestParams) (EyeTest, error)
	UpdateLastLogin(ctx context.Context, id int64) error
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) (Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
	UpdatePurchaseBillPayment(ctx context.Context, arg UpdatePurchaseBillPaymentParams) (PurchaseBill, error)
	UpdateRepair(ctx context.Context, arg UpdateRepairParams) (Repair, error)
	UpdateRepairStatus(ctx context.Context, arg UpdateRepairStatusParams) (Repair, error)
	UpdateShopProfile(ctx context.Context, arg UpdateShopProfileParams) (Shop, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error)
	UpdateVendorBalance(ctx context.Context, arg UpdateVendorBalanceParams) error
	UpsertShopSetting(ctx context.Context, arg UpsertShopSettingParams) (ShopSetting, error)
	UpsertTranslation(ctx context.Context, arg UpsertTranslationParams) (TranslationCache, error)
}

var _ Querier = (*Queries)(nil)
