// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailySalesForRange = `-- name: GetDailySalesForRange :many
SELECT 
    DATE(created_at) AS sale_date,
    COALESCE(SUM(grand_total), 0)::decimal(12,2) AS total_sales,
    COUNT(*)::bigint AS order_count
FROM orders
WHERE shop_id = $1 
  AND status != 'cancelled'
  AND created_at >= $2::timestamptz 
  AND created_at <= $3::timestamptz
GROUP BY DATE(created_at)
ORDER BY DATE(created_at) ASC
`

type GetDailySalesForRangeParams struct {
	ShopID  int64              `json:"shop_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
}

type GetDailySalesForRangeRow struct {
	SaleDate   pgtype.Date    `json:"sale_date"`
	TotalSales pgtype.Numeric `json:"total_sales"`
	OrderCount int64          `json:"order_count"`
}

func (q *Queries) GetDailySalesForRange(ctx context.Context, arg GetDailySalesForRangeParams) ([]GetDailySalesForRangeRow, error) {
	rows, err := q.db.Query(ctx, getDailySalesForRange, arg.ShopID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailySalesForRangeRow{}
	for rows.Next() {
		var i GetDailySalesForRangeRow
		if err := rows.Scan(&i.SaleDate, &i.TotalSales, &i.OrderCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDashboardOverviewStats = `-- name: GetDashboardOverviewStats :one
SELECT 
    COALESCE(SUM(o.grand_total) FILTER (WHERE o.created_at >= CURRENT_DATE), 0)::decimal(12,2) AS today_sales,
    COALESCE(SUM(o.grand_total) FILTER (WHERE o.created_at >= CURRENT_DATE - INTERVAL '1 day' AND o.created_at < CURRENT_DATE), 0)::decimal(12,2) AS yesterday_sales,
    COUNT(*) FILTER (WHERE o.created_at >= CURRENT_DATE)::bigint AS today_orders_count,
    COUNT(*) FILTER (WHERE o.created_at >= CURRENT_DATE - INTERVAL '1 day' AND o.created_at < CURRENT_DATE)::bigint AS yesterday_orders_count,
    (SELECT COUNT(*)::bigint FROM customers c WHERE c.shop_id = $1 AND c.is_active = true) AS active_customers,
    COUNT(*) FILTER (WHERE o.status = 'pending')::bigint AS pending_orders,
    (SELECT COUNT(*)::bigint FROM eye_tests et WHERE et.shop_id = $1 AND et.test_date >= CURRENT_DATE) AS today_eye_tests,
    (SELECT COALESCE(SUM(p.current_stock), 0)::bigint FROM products p WHERE p.shop_id = $1 AND p.is_active = true) AS total_inventory_qty
FROM orders o
WHERE o.shop_id = $1
`

type GetDashboardOverviewStatsRow struct {
	TodaySales           pgtype.Numeric `json:"today_sales"`
	YesterdaySales       pgtype.Numeric `json:"yesterday_sales"`
	TodayOrdersCount     int64          `json:"today_orders_count"`
	YesterdayOrdersCount int64          `json:"yesterday_orders_count"`
	ActiveCustomers      int64          `json:"active_customers"`
	PendingOrders        int64          `json:"pending_orders"`
	TodayEyeTests        int64          `json:"today_eye_tests"`
	TotalInventoryQty    int64          `json:"total_inventory_qty"`
}

func (q *Queries) GetDashboardOverviewStats(ctx context.Context, shopID int64) (GetDashboardOverviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardOverviewStats, shopID)
	var i GetDashboardOverviewStatsRow
	err := row.Scan(
		&i.TodaySales,
		&i.YesterdaySales,
		&i.TodayOrdersCount,
		&i.YesterdayOrdersCount,
		&i.ActiveCustomers,
		&i.PendingOrders,
		&i.TodayEyeTests,
		&i.TotalInventoryQty,
	)
	return i, err
}

const getGSTSummaryReport = `-- name: GetGSTSummaryReport :one
SELECT 
    COALESCE(SUM(taxable_amount), 0)::decimal(12,2) AS total_taxable,
    COALESCE(SUM(cgst_amount), 0)::decimal(12,2) AS total_cgst,
    COALESCE(SUM(sgst_amount), 0)::decimal(12,2) AS total_sgst,
    COALESCE(SUM(igst_amount), 0)::decimal(12,2) AS total_igst,
    COALESCE(SUM(total_tax), 0)::decimal(12,2) AS total_tax,
    COALESCE(SUM(grand_total), 0)::decimal(12,2) AS total_gross_sales
FROM orders
WHERE shop_id = $1 
  AND status != 'cancelled'
  AND created_at >= $2::timestamptz 
  AND created_at <= $3::timestamptz
`

type GetGSTSummaryReportParams struct {
	ShopID  int64              `json:"shop_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
}

type GetGSTSummaryReportRow struct {
	TotalTaxable    pgtype.Numeric `json:"total_taxable"`
	TotalCgst       pgtype.Numeric `json:"total_cgst"`
	TotalSgst       pgtype.Numeric `json:"total_sgst"`
	TotalIgst       pgtype.Numeric `json:"total_igst"`
	TotalTax        pgtype.Numeric `json:"total_tax"`
	TotalGrossSales pgtype.Numeric `json:"total_gross_sales"`
}

func (q *Queries) GetGSTSummaryReport(ctx context.Context, arg GetGSTSummaryReportParams) (GetGSTSummaryReportRow, error) {
	row := q.db.QueryRow(ctx, getGSTSummaryReport, arg.ShopID, arg.Column2, arg.Column3)
	var i GetGSTSummaryReportRow
	err := row.Scan(
		&i.TotalTaxable,
		&i.TotalCgst,
		&i.TotalSgst,
		&i.TotalIgst,
		&i.TotalTax,
		&i.TotalGrossSales,
	)
	return i, err
}

const getPaymentModeBreakdown = `-- name: GetPaymentModeBreakdown :many
SELECT 
    payment_mode,
    COALESCE(SUM(amount), 0)::decimal(12,2) AS total_amount,
    COUNT(*)::bigint AS transaction_count
FROM order_payments op
JOIN orders o ON op.order_id = o.id
WHERE o.shop_id = $1
  AND op.payment_date >= $2::timestamptz 
  AND op.payment_date <= $3::timestamptz
GROUP BY payment_mode
ORDER BY total_amount DESC
`

type GetPaymentModeBreakdownParams struct {
	ShopID  int64              `json:"shop_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
}

type GetPaymentModeBreakdownRow struct {
	PaymentMode      string         `json:"payment_mode"`
	TotalAmount      pgtype.Numeric `json:"total_amount"`
	TransactionCount int64          `json:"transaction_count"`
}

func (q *Queries) GetPaymentModeBreakdown(ctx context.Context, arg GetPaymentModeBreakdownParams) ([]GetPaymentModeBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getPaymentModeBreakdown, arg.ShopID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPaymentModeBreakdownRow{}
	for rows.Next() {
		var i GetPaymentModeBreakdownRow
		if err := rows.Scan(&i.PaymentMode, &i.TotalAmount, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockValuationSummary = `-- name: GetStockValuationSummary :one
SELECT 
    COUNT(*)::bigint AS total_products_count,
    COALESCE(SUM(current_stock), 0)::bigint AS total_stock_units,
    COALESCE(SUM(current_stock * purchase_price), 0)::decimal(12,2) AS total_cost_value,
    COALESCE(SUM(current_stock * selling_price), 0)::decimal(12,2) AS total_retail_value
FROM products
WHERE shop_id = $1 AND is_active = true
`

type GetStockValuationSummaryRow struct {
	TotalProductsCount int64          `json:"total_products_count"`
	TotalStockUnits    int64          `json:"total_stock_units"`
	TotalCostValue     pgtype.Numeric `json:"total_cost_value"`
	TotalRetailValue   pgtype.Numeric `json:"total_retail_value"`
}

func (q *Queries) GetStockValuationSummary(ctx context.Context, shopID int64) (GetStockValuationSummaryRow, error) {
	row := q.db.QueryRow(ctx, getStockValuationSummary, shopID)
	var i GetStockValuationSummaryRow
	err := row.Scan(
		&i.TotalProductsCount,
		&i.TotalStockUnits,
		&i.TotalCostValue,
		&i.TotalRetailValue,
	)
	return i, err
}

const getTopSellingProducts = `-- name: GetTopSellingProducts :many
SELECT 
    oi.name AS product_name,
    oi.item_type,
    SUM(oi.quantity)::bigint AS total_quantity_sold,
    SUM(oi.total_price)::decimal(12,2) AS total_revenue
FROM order_items oi
JOIN orders o ON oi.order_id = o.id
WHERE o.shop_id = $1 
  AND o.status != 'cancelled'
  AND o.created_at >= $2::timestamptz 
  AND o.created_at <= $3::timestamptz
GROUP BY oi.name, oi.item_type
ORDER BY total_quantity_sold DESC
LIMIT $4
`

type GetTopSellingProductsParams struct {
	ShopID  int64              `json:"shop_id"`
	Column2 pgtype.Timestamptz `json:"column_2"`
	Column3 pgtype.Timestamptz `json:"column_3"`
	Limit   int32              `json:"limit"`
}

type GetTopSellingProductsRow struct {
	ProductName       string         `json:"product_name"`
	ItemType          string         `json:"item_type"`
	TotalQuantitySold int64          `json:"total_quantity_sold"`
	TotalRevenue      pgtype.Numeric `json:"total_revenue"`
}

func (q *Queries) GetTopSellingProducts(ctx context.Context, arg GetTopSellingProductsParams) ([]GetTopSellingProductsRow, error) {
	rows, err := q.db.Query(ctx, getTopSellingProducts,
		arg.ShopID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopSellingProductsRow{}
	for rows.Next() {
		var i GetTopSellingProductsRow
		if err := rows.Scan(
			&i.ProductName,
			&i.ItemType,
			&i.TotalQuantitySold,
			&i.TotalRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
