// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shop_settings.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getShopSetting = `-- name: GetShopSetting :one
SELECT id, shop_id, setting_key, setting_value, created_at, updated_at FROM shop_settings
WHERE shop_id = $1 AND setting_key = $2 LIMIT 1
`

type GetShopSettingParams struct {
	ShopID     int64  `json:"shop_id"`
	SettingKey string `json:"setting_key"`
}

func (q *Queries) GetShopSetting(ctx context.Context, arg GetShopSettingParams) (ShopSetting, error) {
	row := q.db.QueryRow(ctx, getShopSetting, arg.ShopID, arg.SettingKey)
	var i ShopSetting
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.SettingKey,
		&i.SettingValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShopSettings = `-- name: ListShopSettings :many
SELECT id, shop_id, setting_key, setting_value, created_at, updated_at FROM shop_settings
WHERE shop_id = $1
ORDER BY setting_key ASC
`

func (q *Queries) ListShopSettings(ctx context.Context, shopID int64) ([]ShopSetting, error) {
	rows, err := q.db.Query(ctx, listShopSettings, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ShopSetting{}
	for rows.Next() {
		var i ShopSetting
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.SettingKey,
			&i.SettingValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertShopSetting = `-- name: UpsertShopSetting :one
INSERT INTO shop_settings (
    shop_id, setting_key, setting_value
) VALUES (
    $1, $2, $3
)
ON CONFLICT (shop_id, setting_key)
DO UPDATE SET setting_value = $3, updated_at = now()
RETURNING id, shop_id, setting_key, setting_value, created_at, updated_at
`

type UpsertShopSettingParams struct {
	ShopID       int64       `json:"shop_id"`
	SettingKey   string      `json:"setting_key"`
	SettingValue pgtype.Text `json:"setting_value"`
}

func (q *Queries) UpsertShopSetting(ctx context.Context, arg UpsertShopSettingParams) (ShopSetting, error) {
	row := q.db.QueryRow(ctx, upsertShopSetting, arg.ShopID, arg.SettingKey, arg.SettingValue)
	var i ShopSetting
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.SettingKey,
		&i.SettingValue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
