// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shops.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getShopByID = `-- name: GetShopByID :one
SELECT id, name, phone, email, address_line1, address_line2, city, state, pin_code, gstin, logo_url, invoice_prefix, invoice_next_number, order_prefix, order_next_number, currency_symbol, default_tax_rate, optometrist_name, eye_testing_fee, terms_and_conditions, language, created_at, updated_at FROM shops
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetShopByID(ctx context.Context, id int64) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PinCode,
		&i.Gstin,
		&i.LogoUrl,
		&i.InvoicePrefix,
		&i.InvoiceNextNumber,
		&i.OrderPrefix,
		&i.OrderNextNumber,
		&i.CurrencySymbol,
		&i.DefaultTaxRate,
		&i.OptometristName,
		&i.EyeTestingFee,
		&i.TermsAndConditions,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementAndGetNextInvoiceNumber = `-- name: IncrementAndGetNextInvoiceNumber :one
UPDATE shops
SET invoice_next_number = invoice_next_number + 1, updated_at = now()
WHERE id = $1
RETURNING invoice_prefix, invoice_next_number - 1 AS invoice_number
`

type IncrementAndGetNextInvoiceNumberRow struct {
	InvoicePrefix pgtype.Text `json:"invoice_prefix"`
	InvoiceNumber int32       `json:"invoice_number"`
}

func (q *Queries) IncrementAndGetNextInvoiceNumber(ctx context.Context, id int64) (IncrementAndGetNextInvoiceNumberRow, error) {
	row := q.db.QueryRow(ctx, incrementAndGetNextInvoiceNumber, id)
	var i IncrementAndGetNextInvoiceNumberRow
	err := row.Scan(&i.InvoicePrefix, &i.InvoiceNumber)
	return i, err
}

const incrementAndGetNextOrderNumber = `-- name: IncrementAndGetNextOrderNumber :one
UPDATE shops
SET order_next_number = order_next_number + 1, updated_at = now()
WHERE id = $1
RETURNING order_prefix, order_next_number - 1 AS order_number
`

type IncrementAndGetNextOrderNumberRow struct {
	OrderPrefix pgtype.Text `json:"order_prefix"`
	OrderNumber int32       `json:"order_number"`
}

func (q *Queries) IncrementAndGetNextOrderNumber(ctx context.Context, id int64) (IncrementAndGetNextOrderNumberRow, error) {
	row := q.db.QueryRow(ctx, incrementAndGetNextOrderNumber, id)
	var i IncrementAndGetNextOrderNumberRow
	err := row.Scan(&i.OrderPrefix, &i.OrderNumber)
	return i, err
}

const updateShopProfile = `-- name: UpdateShopProfile :one
UPDATE shops
SET 
    name = $2,
    phone = $3,
    email = $4,
    address_line1 = $5,
    address_line2 = $6,
    city = $7,
    state = $8,
    pin_code = $9,
    gstin = $10,
    logo_url = $11,
    invoice_prefix = $12,
    order_prefix = $13,
    currency_symbol = $14,
    default_tax_rate = $15,
    optometrist_name = $16,
    eye_testing_fee = $17,
    terms_and_conditions = $18,
    language = $19,
    updated_at = now()
WHERE id = $1
RETURNING id, name, phone, email, address_line1, address_line2, city, state, pin_code, gstin, logo_url, invoice_prefix, invoice_next_number, order_prefix, order_next_number, currency_symbol, default_tax_rate, optometrist_name, eye_testing_fee, terms_and_conditions, language, created_at, updated_at
`

type UpdateShopProfileParams struct {
	ID                 int64          `json:"id"`
	Name               string         `json:"name"`
	Phone              pgtype.Text    `json:"phone"`
	Email              pgtype.Text    `json:"email"`
	AddressLine1       pgtype.Text    `json:"address_line1"`
	AddressLine2       pgtype.Text    `json:"address_line2"`
	City               pgtype.Text    `json:"city"`
	State              pgtype.Text    `json:"state"`
	PinCode            pgtype.Text    `json:"pin_code"`
	Gstin              pgtype.Text    `json:"gstin"`
	LogoUrl            pgtype.Text    `json:"logo_url"`
	InvoicePrefix      pgtype.Text    `json:"invoice_prefix"`
	OrderPrefix        pgtype.Text    `json:"order_prefix"`
	CurrencySymbol     pgtype.Text    `json:"currency_symbol"`
	DefaultTaxRate     pgtype.Numeric `json:"default_tax_rate"`
	OptometristName    pgtype.Text    `json:"optometrist_name"`
	EyeTestingFee      pgtype.Numeric `json:"eye_testing_fee"`
	TermsAndConditions pgtype.Text    `json:"terms_and_conditions"`
	Language           pgtype.Text    `json:"language"`
}

func (q *Queries) UpdateShopProfile(ctx context.Context, arg UpdateShopProfileParams) (Shop, error) {
	row := q.db.QueryRow(ctx, updateShopProfile,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.State,
		arg.PinCode,
		arg.Gstin,
		arg.LogoUrl,
		arg.InvoicePrefix,
		arg.OrderPrefix,
		arg.CurrencySymbol,
		arg.DefaultTaxRate,
		arg.OptometristName,
		arg.EyeTestingFee,
		arg.TermsAndConditions,
		arg.Language,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.State,
		&i.PinCode,
		&i.Gstin,
		&i.LogoUrl,
		&i.InvoicePrefix,
		&i.InvoiceNextNumber,
		&i.OrderPrefix,
		&i.OrderNextNumber,
		&i.CurrencySymbol,
		&i.DefaultTaxRate,
		&i.OptometristName,
		&i.EyeTestingFee,
		&i.TermsAndConditions,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
