// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock_movements.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO stock_movements (
    shop_id, product_id, movement_type, quantity, reference_type, reference_id, notes, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, shop_id, product_id, movement_type, quantity, reference_type, reference_id, notes, created_by, created_at
`

type CreateStockMovementParams struct {
	ShopID        int64       `json:"shop_id"`
	ProductID     int64       `json:"product_id"`
	MovementType  string      `json:"movement_type"`
	Quantity      int32       `json:"quantity"`
	ReferenceType pgtype.Text `json:"reference_type"`
	ReferenceID   pgtype.Int8 `json:"reference_id"`
	Notes         pgtype.Text `json:"notes"`
	CreatedBy     pgtype.Int8 `json:"created_by"`
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, createStockMovement,
		arg.ShopID,
		arg.ProductID,
		arg.MovementType,
		arg.Quantity,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Notes,
		arg.CreatedBy,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.ProductID,
		&i.MovementType,
		&i.Quantity,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listStockMovements = `-- name: ListStockMovements :many
SELECT sm.id, sm.shop_id, sm.product_id, sm.movement_type, sm.quantity, sm.reference_type, sm.reference_id, sm.notes, sm.created_by, sm.created_at, p.name as product_name, p.sku as product_sku, u.full_name as created_by_name
FROM stock_movements sm
JOIN products p ON sm.product_id = p.id
LEFT JOIN users u ON sm.created_by = u.id
WHERE sm.shop_id = $1
ORDER BY sm.created_at DESC
LIMIT $2 OFFSET $3
`

type ListStockMovementsParams struct {
	ShopID int64 `json:"shop_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListStockMovementsRow struct {
	ID            int64              `json:"id"`
	ShopID        int64              `json:"shop_id"`
	ProductID     int64              `json:"product_id"`
	MovementType  string             `json:"movement_type"`
	Quantity      int32              `json:"quantity"`
	ReferenceType pgtype.Text        `json:"reference_type"`
	ReferenceID   pgtype.Int8        `json:"reference_id"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ProductName   string             `json:"product_name"`
	ProductSku    pgtype.Text        `json:"product_sku"`
	CreatedByName pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListStockMovements(ctx context.Context, arg ListStockMovementsParams) ([]ListStockMovementsRow, error) {
	rows, err := q.db.Query(ctx, listStockMovements, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockMovementsRow{}
	for rows.Next() {
		var i ListStockMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ProductID,
			&i.MovementType,
			&i.Quantity,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductSku,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovementsByProduct = `-- name: ListStockMovementsByProduct :many
SELECT sm.id, sm.shop_id, sm.product_id, sm.movement_type, sm.quantity, sm.reference_type, sm.reference_id, sm.notes, sm.created_by, sm.created_at, u.full_name as created_by_name
FROM stock_movements sm
LEFT JOIN users u ON sm.created_by = u.id
WHERE sm.product_id = $1 AND sm.shop_id = $2
ORDER BY sm.created_at DESC
LIMIT $3 OFFSET $4
`

type ListStockMovementsByProductParams struct {
	ProductID int64 `json:"product_id"`
	ShopID    int64 `json:"shop_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListStockMovementsByProductRow struct {
	ID            int64              `json:"id"`
	ShopID        int64              `json:"shop_id"`
	ProductID     int64              `json:"product_id"`
	MovementType  string             `json:"movement_type"`
	Quantity      int32              `json:"quantity"`
	ReferenceType pgtype.Text        `json:"reference_type"`
	ReferenceID   pgtype.Int8        `json:"reference_id"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedBy     pgtype.Int8        `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedByName pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListStockMovementsByProduct(ctx context.Context, arg ListStockMovementsByProductParams) ([]ListStockMovementsByProductRow, error) {
	rows, err := q.db.Query(ctx, listStockMovementsByProduct,
		arg.ProductID,
		arg.ShopID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockMovementsByProductRow{}
	for rows.Next() {
		var i ListStockMovementsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.ProductID,
			&i.MovementType,
			&i.Quantity,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
