// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: translation_cache.sql

package pgdb

import (
	"context"
)

const getAllTranslationsForLanguage = `-- name: GetAllTranslationsForLanguage :many
SELECT source_text, translated_text FROM translation_cache
WHERE source_lang = $1 AND target_lang = $2
`

type GetAllTranslationsForLanguageParams struct {
	SourceLang string `json:"source_lang"`
	TargetLang string `json:"target_lang"`
}

type GetAllTranslationsForLanguageRow struct {
	SourceText     string `json:"source_text"`
	TranslatedText string `json:"translated_text"`
}

func (q *Queries) GetAllTranslationsForLanguage(ctx context.Context, arg GetAllTranslationsForLanguageParams) ([]GetAllTranslationsForLanguageRow, error) {
	rows, err := q.db.Query(ctx, getAllTranslationsForLanguage, arg.SourceLang, arg.TargetLang)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllTranslationsForLanguageRow{}
	for rows.Next() {
		var i GetAllTranslationsForLanguageRow
		if err := rows.Scan(&i.SourceText, &i.TranslatedText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatchTranslations = `-- name: GetBatchTranslations :many
SELECT source_text, translated_text FROM translation_cache
WHERE source_lang = $1 AND target_lang = $2 AND source_text = ANY($3::text[])
`

type GetBatchTranslationsParams struct {
	SourceLang  string   `json:"source_lang"`
	TargetLang  string   `json:"target_lang"`
	SourceTexts []string `json:"source_texts"`
}

type GetBatchTranslationsRow struct {
	SourceText     string `json:"source_text"`
	TranslatedText string `json:"translated_text"`
}

func (q *Queries) GetBatchTranslations(ctx context.Context, arg GetBatchTranslationsParams) ([]GetBatchTranslationsRow, error) {
	rows, err := q.db.Query(ctx, getBatchTranslations, arg.SourceLang, arg.TargetLang, arg.SourceTexts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBatchTranslationsRow{}
	for rows.Next() {
		var i GetBatchTranslationsRow
		if err := rows.Scan(&i.SourceText, &i.TranslatedText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTranslation = `-- name: GetTranslation :one
SELECT id, source_text, source_lang, target_lang, translated_text, created_at, updated_at FROM translation_cache
WHERE source_lang = $1 AND target_lang = $2 AND source_text = $3
LIMIT 1
`

type GetTranslationParams struct {
	SourceLang string `json:"source_lang"`
	TargetLang string `json:"target_lang"`
	SourceText string `json:"source_text"`
}

func (q *Queries) GetTranslation(ctx context.Context, arg GetTranslationParams) (TranslationCache, error) {
	row := q.db.QueryRow(ctx, getTranslation, arg.SourceLang, arg.TargetLang, arg.SourceText)
	var i TranslationCache
	err := row.Scan(
		&i.ID,
		&i.SourceText,
		&i.SourceLang,
		&i.TargetLang,
		&i.TranslatedText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTranslation = `-- name: UpsertTranslation :one
INSERT INTO translation_cache (
    source_text, source_lang, target_lang, translated_text
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (source_lang, target_lang, MD5(source_text))
DO UPDATE SET 
    translated_text = EXCLUDED.translated_text,
    updated_at = now()
RETURNING id, source_text, source_lang, target_lang, translated_text, created_at, updated_at
`

type UpsertTranslationParams struct {
	SourceText     string `json:"source_text"`
	SourceLang     string `json:"source_lang"`
	TargetLang     string `json:"target_lang"`
	TranslatedText string `json:"translated_text"`
}

func (q *Queries) UpsertTranslation(ctx context.Context, arg UpsertTranslationParams) (TranslationCache, error) {
	row := q.db.QueryRow(ctx, upsertTranslation,
		arg.SourceText,
		arg.SourceLang,
		arg.TargetLang,
		arg.TranslatedText,
	)
	var i TranslationCache
	err := row.Scan(
		&i.ID,
		&i.SourceText,
		&i.SourceLang,
		&i.TargetLang,
		&i.TranslatedText,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
