// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    shop_id, username, password, full_name, email, phone, role, profile_image_url, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, shop_id, username, password, full_name, email, phone, role, profile_image_url, is_active, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ShopID          int64       `json:"shop_id"`
	Username        string      `json:"username"`
	Password        string      `json:"password"`
	FullName        string      `json:"full_name"`
	Email           pgtype.Text `json:"email"`
	Phone           pgtype.Text `json:"phone"`
	Role            string      `json:"role"`
	ProfileImageUrl pgtype.Text `json:"profile_image_url"`
	IsActive        bool        `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ShopID,
		arg.Username,
		arg.Password,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.ProfileImageUrl,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.ProfileImageUrl,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, shop_id, username, password, full_name, email, phone, role, profile_image_url, is_active, last_login_at, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.ProfileImageUrl,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, shop_id, username, password, full_name, email, phone, role, profile_image_url, is_active, last_login_at, created_at, updated_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.ProfileImageUrl,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByShop = `-- name: ListUsersByShop :many
SELECT id, shop_id, username, password, full_name, email, phone, role, profile_image_url, is_active, last_login_at, created_at, updated_at FROM users
WHERE shop_id = $1
ORDER BY id ASC
`

func (q *Queries) ListUsersByShop(ctx context.Context, shopID int64) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByShop, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Username,
			&i.Password,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.ProfileImageUrl,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    full_name = $2,
    email = $3,
    phone = $4,
    role = $5,
    profile_image_url = $6,
    is_active = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, shop_id, username, password, full_name, email, phone, role, profile_image_url, is_active, last_login_at, created_at, updated_at
`

type UpdateUserParams struct {
	ID              int64       `json:"id"`
	FullName        string      `json:"full_name"`
	Email           pgtype.Text `json:"email"`
	Phone           pgtype.Text `json:"phone"`
	Role            string      `json:"role"`
	ProfileImageUrl pgtype.Text `json:"profile_image_url"`
	IsActive        bool        `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.Role,
		arg.ProfileImageUrl,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.ProfileImageUrl,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :one
UPDATE users
SET password = $2, updated_at = now()
WHERE id = $1
RETURNING id, shop_id, username, password, full_name, email, phone, role, profile_image_url, is_active, last_login_at, created_at, updated_at
`

type UpdateUserPasswordParams struct {
	ID       int64  `json:"id"`
	Password string `json:"password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPassword, arg.ID, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Username,
		&i.Password,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.ProfileImageUrl,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
