// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendors.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (
    shop_id, name, contact_person, phone, email, gstin, address, city, state, pin_code, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
RETURNING id, shop_id, name, contact_person, phone, email, gstin, address, city, state, pin_code, notes, outstanding_balance, is_active, created_at, updated_at
`

type CreateVendorParams struct {
	ShopID        int64       `json:"shop_id"`
	Name          string      `json:"name"`
	ContactPerson pgtype.Text `json:"contact_person"`
	Phone         pgtype.Text `json:"phone"`
	Email         pgtype.Text `json:"email"`
	Gstin         pgtype.Text `json:"gstin"`
	Address       pgtype.Text `json:"address"`
	City          pgtype.Text `json:"city"`
	State         pgtype.Text `json:"state"`
	PinCode       pgtype.Text `json:"pin_code"`
	Notes         pgtype.Text `json:"notes"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor,
		arg.ShopID,
		arg.Name,
		arg.ContactPerson,
		arg.Phone,
		arg.Email,
		arg.Gstin,
		arg.Address,
		arg.City,
		arg.State,
		arg.PinCode,
		arg.Notes,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.ContactPerson,
		&i.Phone,
		&i.Email,
		&i.Gstin,
		&i.Address,
		&i.City,
		&i.State,
		&i.PinCode,
		&i.Notes,
		&i.OutstandingBalance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVendorByID = `-- name: GetVendorByID :one
SELECT id, shop_id, name, contact_person, phone, email, gstin, address, city, state, pin_code, notes, outstanding_balance, is_active, created_at, updated_at FROM vendors
WHERE id = $1 AND shop_id = $2 LIMIT 1
`

type GetVendorByIDParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

func (q *Queries) GetVendorByID(ctx context.Context, arg GetVendorByIDParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByID, arg.ID, arg.ShopID)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.ContactPerson,
		&i.Phone,
		&i.Email,
		&i.Gstin,
		&i.Address,
		&i.City,
		&i.State,
		&i.PinCode,
		&i.Notes,
		&i.OutstandingBalance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVendors = `-- name: ListVendors :many
SELECT id, shop_id, name, contact_person, phone, email, gstin, address, city, state, pin_code, notes, outstanding_balance, is_active, created_at, updated_at FROM vendors
WHERE shop_id = $1 AND is_active = true
ORDER BY name ASC
`

func (q *Queries) ListVendors(ctx context.Context, shopID int64) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listVendors, shopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vendor{}
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.Name,
			&i.ContactPerson,
			&i.Phone,
			&i.Email,
			&i.Gstin,
			&i.Address,
			&i.City,
			&i.State,
			&i.PinCode,
			&i.Notes,
			&i.OutstandingBalance,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVendor = `-- name: SoftDeleteVendor :exec
UPDATE vendors
SET is_active = false, updated_at = now()
WHERE id = $1 AND shop_id = $2
`

type SoftDeleteVendorParams struct {
	ID     int64 `json:"id"`
	ShopID int64 `json:"shop_id"`
}

func (q *Queries) SoftDeleteVendor(ctx context.Context, arg SoftDeleteVendorParams) error {
	_, err := q.db.Exec(ctx, softDeleteVendor, arg.ID, arg.ShopID)
	return err
}

const updateVendor = `-- name: UpdateVendor :one
UPDATE vendors
SET 
    name = $3,
    contact_person = $4,
    phone = $5,
    email = $6,
    gstin = $7,
    address = $8,
    city = $9,
    state = $10,
    pin_code = $11,
    notes = $12,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
RETURNING id, shop_id, name, contact_person, phone, email, gstin, address, city, state, pin_code, notes, outstanding_balance, is_active, created_at, updated_at
`

type UpdateVendorParams struct {
	ID            int64       `json:"id"`
	ShopID        int64       `json:"shop_id"`
	Name          string      `json:"name"`
	ContactPerson pgtype.Text `json:"contact_person"`
	Phone         pgtype.Text `json:"phone"`
	Email         pgtype.Text `json:"email"`
	Gstin         pgtype.Text `json:"gstin"`
	Address       pgtype.Text `json:"address"`
	City          pgtype.Text `json:"city"`
	State         pgtype.Text `json:"state"`
	PinCode       pgtype.Text `json:"pin_code"`
	Notes         pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateVendor(ctx context.Context, arg UpdateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, updateVendor,
		arg.ID,
		arg.ShopID,
		arg.Name,
		arg.ContactPerson,
		arg.Phone,
		arg.Email,
		arg.Gstin,
		arg.Address,
		arg.City,
		arg.State,
		arg.PinCode,
		arg.Notes,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.Name,
		&i.ContactPerson,
		&i.Phone,
		&i.Email,
		&i.Gstin,
		&i.Address,
		&i.City,
		&i.State,
		&i.PinCode,
		&i.Notes,
		&i.OutstandingBalance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVendorBalance = `-- name: UpdateVendorBalance :exec
UPDATE vendors
SET 
    outstanding_balance = outstanding_balance + $3,
    updated_at = now()
WHERE id = $1 AND shop_id = $2
`

type UpdateVendorBalanceParams struct {
	ID                 int64          `json:"id"`
	ShopID             int64          `json:"shop_id"`
	OutstandingBalance pgtype.Numeric `json:"outstanding_balance"`
}

func (q *Queries) UpdateVendorBalance(ctx context.Context, arg UpdateVendorBalanceParams) error {
	_, err := q.db.Exec(ctx, updateVendorBalance, arg.ID, arg.ShopID, arg.OutstandingBalance)
	return err
}
