// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vendor_payments.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVendorPayment = `-- name: CreateVendorPayment :one
INSERT INTO vendor_payments (
    shop_id, vendor_id, purchase_bill_id, amount, payment_mode, transaction_ref, notes, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, shop_id, vendor_id, purchase_bill_id, amount, payment_mode, transaction_ref, payment_date, notes, created_by, created_at
`

type CreateVendorPaymentParams struct {
	ShopID         int64          `json:"shop_id"`
	VendorID       int64          `json:"vendor_id"`
	PurchaseBillID pgtype.Int8    `json:"purchase_bill_id"`
	Amount         pgtype.Numeric `json:"amount"`
	PaymentMode    string         `json:"payment_mode"`
	TransactionRef pgtype.Text    `json:"transaction_ref"`
	Notes          pgtype.Text    `json:"notes"`
	CreatedBy      pgtype.Int8    `json:"created_by"`
}

func (q *Queries) CreateVendorPayment(ctx context.Context, arg CreateVendorPaymentParams) (VendorPayment, error) {
	row := q.db.QueryRow(ctx, createVendorPayment,
		arg.ShopID,
		arg.VendorID,
		arg.PurchaseBillID,
		arg.Amount,
		arg.PaymentMode,
		arg.TransactionRef,
		arg.Notes,
		arg.CreatedBy,
	)
	var i VendorPayment
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.VendorID,
		&i.PurchaseBillID,
		&i.Amount,
		&i.PaymentMode,
		&i.TransactionRef,
		&i.PaymentDate,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listVendorPayments = `-- name: ListVendorPayments :many
SELECT vp.id, vp.shop_id, vp.vendor_id, vp.purchase_bill_id, vp.amount, vp.payment_mode, vp.transaction_ref, vp.payment_date, vp.notes, vp.created_by, vp.created_at, v.name as vendor_name, u.full_name as created_by_name
FROM vendor_payments vp
JOIN vendors v ON vp.vendor_id = v.id
LEFT JOIN users u ON vp.created_by = u.id
WHERE vp.shop_id = $1
ORDER BY vp.payment_date DESC
LIMIT $2 OFFSET $3
`

type ListVendorPaymentsParams struct {
	ShopID int64 `json:"shop_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListVendorPaymentsRow struct {
	ID             int64              `json:"id"`
	ShopID         int64              `json:"shop_id"`
	VendorID       int64              `json:"vendor_id"`
	PurchaseBillID pgtype.Int8        `json:"purchase_bill_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	PaymentMode    string             `json:"payment_mode"`
	TransactionRef pgtype.Text        `json:"transaction_ref"`
	PaymentDate    pgtype.Timestamptz `json:"payment_date"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	VendorName     string             `json:"vendor_name"`
	CreatedByName  pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListVendorPayments(ctx context.Context, arg ListVendorPaymentsParams) ([]ListVendorPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listVendorPayments, arg.ShopID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVendorPaymentsRow{}
	for rows.Next() {
		var i ListVendorPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.VendorID,
			&i.PurchaseBillID,
			&i.Amount,
			&i.PaymentMode,
			&i.TransactionRef,
			&i.PaymentDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.VendorName,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorPaymentsByVendor = `-- name: ListVendorPaymentsByVendor :many
SELECT vp.id, vp.shop_id, vp.vendor_id, vp.purchase_bill_id, vp.amount, vp.payment_mode, vp.transaction_ref, vp.payment_date, vp.notes, vp.created_by, vp.created_at, u.full_name as created_by_name
FROM vendor_payments vp
LEFT JOIN users u ON vp.created_by = u.id
WHERE vp.vendor_id = $1 AND vp.shop_id = $2
ORDER BY vp.payment_date DESC
`

type ListVendorPaymentsByVendorParams struct {
	VendorID int64 `json:"vendor_id"`
	ShopID   int64 `json:"shop_id"`
}

type ListVendorPaymentsByVendorRow struct {
	ID             int64              `json:"id"`
	ShopID         int64              `json:"shop_id"`
	VendorID       int64              `json:"vendor_id"`
	PurchaseBillID pgtype.Int8        `json:"purchase_bill_id"`
	Amount         pgtype.Numeric     `json:"amount"`
	PaymentMode    string             `json:"payment_mode"`
	TransactionRef pgtype.Text        `json:"transaction_ref"`
	PaymentDate    pgtype.Timestamptz `json:"payment_date"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedBy      pgtype.Int8        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CreatedByName  pgtype.Text        `json:"created_by_name"`
}

func (q *Queries) ListVendorPaymentsByVendor(ctx context.Context, arg ListVendorPaymentsByVendorParams) ([]ListVendorPaymentsByVendorRow, error) {
	rows, err := q.db.Query(ctx, listVendorPaymentsByVendor, arg.VendorID, arg.ShopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVendorPaymentsByVendorRow{}
	for rows.Next() {
		var i ListVendorPaymentsByVendorRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.VendorID,
			&i.PurchaseBillID,
			&i.Amount,
			&i.PaymentMode,
			&i.TransactionRef,
			&i.PaymentDate,
			&i.Notes,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
